"""SR 11-7 / SR 26-02 model documentation generator.

Produces a Markdown document summarizing a
:class:`evidentia_core.models.model_risk.ModelInventory` record in
the structure regulated-financial-services model-risk-management
programs are required to maintain per OCC Bulletin 2011-12 / FRB
SR 11-7 (active 2011-2026) and OCC Bulletin 2026-13a / FRB SR 26-02
(supersession; April 2026 — active for non-generative-AI models).

Section sequence aligns with the SR 11-7 §III.B "Model Development,
Implementation, and Use" framework:

  1. Model identification + ownership
  2. Purpose and intended use
  3. Methodology and design
  4. Inputs (data + provenance)
  5. Outputs (decisions consumed downstream)
  6. Assumptions and limitations
  7. Validation history
  8. Monitoring + retirement plan
  9. Audit trail (linked AI-generated risk statements via
     ``RiskStatement.model_inventory_ref`` from v0.7.10 P0.6.4)

Output is plain Markdown — diff-able, version-controllable, and
portable across every common auditor toolchain (Word via pandoc,
PDF via pandoc, HTML, plain text).
"""

from __future__ import annotations

from datetime import date

from evidentia_core.models.model_risk import ModelInventory


def _format_date(d: date | None) -> str:
    """Render a date in ISO-8601 with a 'Not set' fallback for None."""
    return d.isoformat() if d else "_Not set_"


def _format_optional_text(text: str | None) -> str:
    """Render free-text or 'Not specified' fallback."""
    return text if text and text.strip() else "_Not specified_"


def generate_model_documentation(model: ModelInventory) -> str:
    """Generate SR 11-7-aligned model documentation as Markdown.

    Parameters
    ----------
    model
        The ModelInventory record to document.

    Returns
    -------
    str
        Markdown document. Caller decides where to write it
        (file, REST response body, etc.).

    Notes
    -----
    The output is deterministic — same input produces the same
    output character-for-character. Operators can therefore commit
    the generated docs to git and audit-diff them across model
    revisions.
    """
    next_due = _format_date(model.next_validation_due)
    last_validation = _format_date(model.last_validation_date)
    sections: list[str] = []

    # ── §1 Identification ─────────────────────────────────────────
    sections.append(
        f"# Model Documentation — {model.name}\n\n"
        f"_SR 11-7 / SR 26-02 / OCC Bulletin 2011-12 / OCC Bulletin "
        f"2026-13a aligned model documentation. Generated by Evidentia "
        f"v{model.evidentia_version} from ModelInventory record._\n\n"
        f"## 1. Identification\n\n"
        f"| Field | Value |\n"
        f"| --- | --- |\n"
        f"| Model ID | `{model.id}` |\n"
        f"| Name | {model.name} |\n"
        f"| Tier | {model.tier} |\n"
        f"| Methodology | {model.methodology} |\n"
        f"| Provenance | {model.vendor_or_internal} |\n"
        f"| Owner | {model.owner} |\n"
        f"| Vendor ID | "
        f"{model.vendor_id if model.vendor_id else '_(internal model)_'} |\n"
        f"| Created | {model.created_at.isoformat()} |\n"
        f"| Last updated | {model.updated_at.isoformat()} |\n"
        f"| Last validation | {last_validation} |\n"
        f"| Next validation due | {next_due} |\n"
    )

    # ── §2 Purpose and intended use ──────────────────────────────
    sections.append(
        f"## 2. Purpose and intended use\n\n"
        f"{model.purpose}\n"
    )

    # ── §3 Methodology and design ────────────────────────────────
    sections.append(
        f"## 3. Methodology and design\n\n"
        f"**Methodology category**: `{model.methodology}`\n\n"
        f"**Tier**: `{model.tier}` — under SR 11-7 §IV "
        f"materiality framing, "
        f"{_tier_text(model.tier)}.\n"
    )

    # ── §4 Inputs ────────────────────────────────────────────────
    if model.inputs:
        input_rows = "\n".join(
            f"| {i.name} | {i.source_system} | "
            f"{_format_optional_text(i.transformation)} | "
            f"{_format_optional_text(i.data_classification)} | "
            f"{_format_optional_text(i.refresh_cadence)} |"
            for i in model.inputs
        )
        sections.append(
            "## 4. Inputs\n\n"
            "| Name | Source system | Transformation | Classification | Refresh |\n"
            "| --- | --- | --- | --- | --- |\n"
            f"{input_rows}\n"
        )
    else:
        sections.append(
            "## 4. Inputs\n\n"
            "_No inputs recorded. Per SR 11-7 §III.B.2, model "
            "documentation must describe the data used by the model. "
            "Update the inventory with `evidentia model-risk model edit "
            f"{model.id} --from-yaml ...`._\n"
        )

    # ── §5 Outputs ───────────────────────────────────────────────
    if model.outputs:
        output_rows = "\n".join(
            f"| {o.name} | {o.decision_type} | "
            f"{', '.join(o.downstream_consumers) if o.downstream_consumers else '_None_'} |"
            for o in model.outputs
        )
        sections.append(
            "## 5. Outputs\n\n"
            "| Name | Decision type | Downstream consumers |\n"
            "| --- | --- | --- |\n"
            f"{output_rows}\n"
        )
    else:
        sections.append(
            "## 5. Outputs\n\n"
            "_No outputs recorded._\n"
        )

    # ── §6 Assumptions and limitations ───────────────────────────
    # SR 11-7 §III.A.4 requires documentation of model assumptions
    # + limitations. The current ModelInventory schema (v0.7.10
    # P0.6.1) carries these as free-text under `notes`; a future
    # slice may promote them to structured `assumptions: list[str]`
    # + `limitations: list[str]` fields.
    sections.append(
        "## 6. Assumptions and limitations\n\n"
        f"{_format_optional_text(model.notes)}\n"
    )

    # ── §7 Validation history ────────────────────────────────────
    if model.validation_findings:
        finding_rows = "\n".join(
            f"| {f.detected_at.isoformat()} | {f.severity} | "
            f"{f.status} | {f.title} |"
            for f in model.validation_findings
        )
        sections.append(
            "## 7. Validation history\n\n"
            f"**Last validation**: {last_validation}  \n"
            f"**Next validation due**: {next_due}\n\n"
            "| Date | Severity | Status | Finding |\n"
            "| --- | --- | --- | --- |\n"
            f"{finding_rows}\n"
        )
    else:
        sections.append(
            "## 7. Validation history\n\n"
            f"**Last validation**: {last_validation}  \n"
            f"**Next validation due**: {next_due}\n\n"
            "_No validation findings recorded yet. Per SR 11-7 §V, "
            "Tier-1 / Tier-2 models require independent validation on "
            "a tier-driven cadence (Tier 1 annual / Tier 2 biennial / "
            "Tier 3 triennial)._\n"
        )

    # ── §8 Monitoring and retirement ────────────────────────────
    sections.append(
        "## 8. Monitoring and retirement plan\n\n"
        f"{_format_optional_text(model.retirement_plan)}\n"
    )

    # ── §9 Audit trail (linked AI risk statements) ───────────────
    sections.append(
        "## 9. Audit trail\n\n"
        "Risk statements generated by AI features that reference "
        f"this model inventory entry carry "
        f"`model_inventory_ref={model.id!r}`. "
        "The full audit trail is reconstructible by querying the "
        "risk-store for risk statements whose `model_inventory_ref` "
        "field matches this model's `id`. See "
        "`evidentia_core.models.risk.RiskStatement.model_inventory_ref` "
        "(v0.7.10 P0.6.4 SR 11-7 / SR 26-02 linkage).\n"
    )

    return "\n".join(sections)


def _tier_text(tier_value: str) -> str:
    """Map tier enum value to SR 11-7 materiality narrative."""
    return {
        "tier_1": (
            "this model is HIGH materiality with substantial impact on "
            "earnings, capital, or strategic decisions; it requires "
            "annual independent validation and the highest level of "
            "documentation rigor"
        ),
        "tier_2": (
            "this model is MODERATE materiality; it requires biennial "
            "independent validation and standard documentation rigor"
        ),
        "tier_3": (
            "this model is LOW materiality; it requires triennial "
            "validation and minimum documentation rigor"
        ),
    }.get(tier_value, "tier classification unrecognized")
