"""Content tests for the bundled FedRAMP CR26 KSI catalog.

v0.11 Wave 2 — generated by ``scripts/catalogs/gen_fedramp_ksi.py`` from
``FedRAMP/rules`` ``fedramp-consolidated-rules.json`` at the commit
pinned in ``evidentia_core/fedramp/schemas/UPSTREAM.json`` (dataset
version 2026.07.14.01). Counts verified against that revision:
10 KSI families, 46 indicators, every family ``status: stable``.

Five indicators (KSI-CNA-EIS, KSI-MLA-ALA, KSI-SVC-PRR, KSI-SVC-RUD,
KSI-SVC-VCM) carry no base statement upstream — they are defined per
certification class (``varies_by_class``; class C holds the canonical
text, class B marks it optional). The generator uses the class-C
statement as the description and preserves every class variant verbatim
in guidance.
"""

from __future__ import annotations

from evidentia_core.catalogs.loader import load_catalog

#: The five upstream indicators defined only via ``varies_by_class``.
CLASS_VARIANT_IDS = {
    "KSI-CNA-EIS",
    "KSI-MLA-ALA",
    "KSI-SVC-PRR",
    "KSI-SVC-RUD",
    "KSI-SVC-VCM",
}


def test_loads_with_46_indicators_across_10_families() -> None:
    catalog = load_catalog("fedramp-ksi-2026")
    assert catalog.framework_id == "fedramp-ksi-2026"
    assert len(catalog.controls) == 46
    assert len(catalog.families) == 10
    assert catalog.tier == "A"
    assert catalog.placeholder is False


def test_family_names_match_upstream() -> None:
    catalog = load_catalog("fedramp-ksi-2026")
    assert set(catalog.families) == {
        "Cybersecurity Education",
        "Change Management",
        "Cloud Native Architecture",
        "Identity and Access Management",
        "Incident Response",
        "Monitoring, Logging, and Auditing",
        "Policy and Inventory",
        "Recovery Planning",
        "Supply Chain Risk",
        "Service Configuration",
    }


def test_spot_check_ksi_ced_rat() -> None:
    catalog = load_catalog("fedramp-ksi-2026")
    control = next(c for c in catalog.controls if c.id == "KSI-CED-RAT")
    assert control.title == "Reviewing All Training"
    assert control.family == "Cybersecurity Education"
    assert "cybersecurity education and training" in control.description
    # The 800-53 mapping is preserved verbatim in guidance.
    assert control.guidance is not None
    assert "cp-3" in control.guidance
    assert "at-2.2" in control.guidance


def test_every_indicator_has_statement_and_mapping_guidance() -> None:
    catalog = load_catalog("fedramp-ksi-2026")
    for control in catalog.controls:
        assert control.description, f"{control.id} has an empty description"
        assert control.guidance and "NIST SP 800-53 Rev 5 mapping" in control.guidance


def test_class_variant_indicators_preserve_variants_in_guidance() -> None:
    catalog = load_catalog("fedramp-ksi-2026")
    by_id = {c.id: c for c in catalog.controls}
    for ksi_id in CLASS_VARIANT_IDS:
        control = by_id[ksi_id]
        assert control.guidance is not None
        assert "Class-B variant statement" in control.guidance
        assert "Class-C variant statement" in control.guidance
        # The description is the canonical (class-C) text — never the
        # "**Optional:**"-prefixed class-B variant.
        assert not control.description.startswith("**Optional:**")


def test_crosswalk_to_800_53_covers_every_indicator() -> None:
    import json
    from pathlib import Path

    from evidentia_core.models.catalog import CrosswalkDefinition

    crosswalk_path = (
        Path(__file__).parents[3]
        / "packages"
        / "evidentia-core"
        / "src"
        / "evidentia_core"
        / "catalogs"
        / "data"
        / "mappings"
        / "fedramp-ksi-2026_to_nist-800-53-rev5.json"
    )
    crosswalk = CrosswalkDefinition.model_validate(json.loads(crosswalk_path.read_text(encoding="utf-8")))
    assert crosswalk.source_framework == "fedramp-ksi-2026"
    assert crosswalk.target_framework == "nist-800-53-rev5"
    assert crosswalk.verification == "self-attested-via-upstream"

    catalog = load_catalog("fedramp-ksi-2026")
    mapped_sources = {m.source_control_id for m in crosswalk.mappings}
    # Two indicators declare NO 800-53 mapping upstream (`controls: []`
    # at the pinned revision) — the crosswalk faithfully omits them.
    unmapped_upstream = {"KSI-CNA-OFA", "KSI-PIY-RES"}
    assert mapped_sources == {c.id for c in catalog.controls} - unmapped_upstream
    # Base-control folding: enhancement citations survive in notes.
    at2 = next(m for m in crosswalk.mappings if m.source_control_id == "KSI-CED-RAT" and m.target_control_id == "AT-2")
    assert "at-2.2" in (at2.notes or "")
