"""Content tests for the bundled FedRAMP CR26 Requirements (FRR) catalog.

v0.12 — generated by ``scripts/catalogs/gen_fedramp_frr.py`` from the
same pinned ``FedRAMP/rules`` ``fedramp-consolidated-rules.json`` the KSI
catalog uses (dataset version 2026.07.14.01). Counts verified against
that revision: 15 rule families, 180 provider-facing rules — the rules
whose upstream ``affects`` list names Providers. Rules addressed to
FedRAMP itself, assessors, or agencies are deliberately excluded: an SDR
is the provider's record, and listing obligations a provider cannot
implement would make the ``conmon ksi`` coverage report noise.

29 rules carry no base statement upstream and are defined only per
certification class (``varies_by_class``). As in the KSI catalog, the
class-C statement is the description and every variant is preserved
verbatim in guidance.
"""

from __future__ import annotations

from evidentia_core.catalogs.loader import load_catalog

CATALOG_ID = "fedramp-frr-2026"


def test_loads_with_180_rules_across_15_families() -> None:
    catalog = load_catalog(CATALOG_ID)
    assert catalog.framework_id == CATALOG_ID
    assert len(catalog.controls) == 180
    assert len(catalog.families) == 15
    assert catalog.tier == "A"
    assert catalog.placeholder is False


def test_family_names_match_upstream() -> None:
    catalog = load_catalog(CATALOG_ID)
    assert set(catalog.families) == {
        "Addressing FedRAMP Communication",
        "Collaborative Continuous Monitoring",
        "Certification Data Sharing",
        "Cryptographic Module Use",
        "Certification Package Overview",
        "FedRAMP Certification",
        "Incident Evaluation and Communication",
        "Independent Verification and Validation",
        "Minimum Assessment Scope",
        "Marketplace Listing",
        "Secure Configuration Guide",
        "Significant Change Notification",
        "Security Decision Record",
        "Vulnerability Detection and Response",
        "Vulnerability Evaluation and Reporting",
    }


def test_only_provider_facing_rules_are_included() -> None:
    """A FedRAMP-addressed rule (affects: [FedRAMP]) must not be present."""
    ids = {c.id for c in load_catalog(CATALOG_ID).controls}
    assert "AFC-FRP-VRE" not in ids  # "FedRAMP MUST send messages…"
    assert "SDR-CSO-FRR" in ids  # "Providers MUST supply a Security Decision Record…"


def test_ids_are_unique_and_sorted_within_family() -> None:
    controls = load_catalog(CATALOG_ID).controls
    ids = [c.id for c in controls]
    assert len(ids) == len(set(ids))
    by_family: dict[str, list[str]] = {}
    for c in controls:
        by_family.setdefault(c.family or "", []).append(c.id)
    for family_ids in by_family.values():
        assert family_ids == sorted(family_ids)


def test_spot_check_sdr_cso_frr() -> None:
    """The rule this whole catalog exists to satisfy."""
    rule = next(c for c in load_catalog(CATALOG_ID).controls if c.id == "SDR-CSO-FRR")
    assert rule.title == "FedRAMP Rules"
    assert rule.description.startswith("Providers MUST supply a Security Decision Record")
    assert rule.family == "Security Decision Record"
    guidance = rule.guidance or ""
    assert "Force: MUST." in guidance
    assert "Applies to all FedRAMP authorizations." in guidance
    assert "following_information" in guidance
    assert "Independent verification." in guidance


def test_every_rule_has_statement_force_and_applicability() -> None:
    for rule in load_catalog(CATALOG_ID).controls:
        assert rule.description, rule.id
        guidance = rule.guidance or ""
        assert "Force: " in guidance, rule.id
        assert "Applies to " in guidance, rule.id


def test_class_variant_rules_preserve_every_variant() -> None:
    controls = load_catalog(CATALOG_ID).controls
    variant_rules = [c for c in controls if "varies_by_class" in (c.guidance or "")]
    assert len(variant_rules) == 29
    ccm = next(c for c in variant_rules if c.id == "CCM-QTR-MTG")
    guidance = ccm.guidance or ""
    # Class A is MAY, class B is SHOULD — both must survive verbatim.
    assert "Class-A variant" in guidance and "force MAY" in guidance
    assert "Class-B variant" in guidance and "force SHOULD" in guidance
