"""Pinned CJIS source cells stay attached to explicitly reviewed reference units."""

from __future__ import annotations

import copy
import hashlib
import importlib.util
import json
import subprocess
import sys
from collections import Counter
from datetime import date
from pathlib import Path
from typing import Any

import pytest
from evidentia_core.catalogs.loader import load_evidentia_catalog
from evidentia_core.gap_analyzer import GapAnalyzer
from evidentia_core.models.catalog import ControlCatalog

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "scripts/catalogs/sources/cjis-v6.1-source.json"
GENERATOR = ROOT / "scripts/catalogs/gen_cjis_companion.py"
CATALOG = ROOT / "packages/evidentia-core/src/evidentia_core/catalogs/data/us-federal/cjis-v6.1.json"
COLUMNS = tuple("ABCDEFGHIJKLMNOPQRSTUVWXY")
LOCATION = "Ver 6.1 Location and New Requirement"
STATEMENT = "Shall Statement / Requirement"

# These digests were independently checked against the archived workbook ZIP XML
# and the reviewed row-disposition ledger. They are not generated by the builder.
PHYSICAL_ROWS_SHA256 = "e65059be26c05ac0fcccb164b741c881b17aa7935436d22eae76b2b568f78bb9"
ASSOCIATION_SHA256 = "4ef8b5d66138cbe3af279d1138c8411f84701139d4758212277530a23d2dbae8"
MERGES_SHA256 = "4250543226582cff7055e4251539f63d2657113cbb17eb937dffa51eaeb6f8e5"


def _digest(value: Any) -> str:
    data = json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(data.encode("ascii")).hexdigest()


@pytest.fixture(scope="module")
def generator() -> Any:
    spec = importlib.util.spec_from_file_location("cjis_companion_generator", GENERATOR)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def projection() -> dict[str, Any]:
    return json.loads(SOURCE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def payload(generator: Any, projection: dict[str, Any]) -> dict[str, Any]:
    return generator.build_catalog(projection)


def _rows(payload: dict[str, Any]) -> dict[int, dict[str, Any]]:
    records = [row for control in payload["controls"] for row in control["source_rows"]]
    assert len(records) == len({r["row"] for r in records}) == 1533
    assert [r["row"] for r in records] == sorted(r["row"] for r in records)
    return {r["row"]: r for r in records}


def _physical_rows(records: dict[int, dict[str, Any]]) -> list[Any]:
    result = []
    for number, row in records.items():
        labels = {col: label for label, col in json.loads(row["provenance"]["columns"]).items()}
        metadata = json.loads(row["provenance"]["cell_metadata"])
        result.append([number, [[c, row["values"][labels[c]], *metadata[c]] for c in COLUMNS]])
    return result


def test_every_source_cell_type_and_format_matches_the_independent_workbook_contract(
    projection: dict[str, Any], payload: dict[str, Any]
) -> None:
    source_tuples = [[r["row"], [[c, *r["cells"][c]] for c in COLUMNS]] for r in projection["rows"]]
    assert _digest(source_tuples) == PHYSICAL_ROWS_SHA256
    retained = _physical_rows(_rows(payload))
    assert _digest(retained) == PHYSICAL_ROWS_SHA256
    assert retained == source_tuples
    assert sum(len(r[1]) for r in retained) == 38325
    assert projection["cell_fields"][3] == "xml_style_id"
    assert projection["headers"][0]["cells"]["X"][3] == 91
    assert projection["xml_cell_styles"][91]["attributes"]["numFmtId"] == "0"
    assert all(row["kind"] == "fragment" and row["sheet"] == "v6.1" for row in _rows(payload).values())
    assert {row["source_sha256"] for row in _rows(payload).values()} == {projection["source_sha256"]}


def test_every_location_and_merge_anchor_matches_independently_reviewed_expectations(payload: dict[str, Any]) -> None:
    associations = []
    merges = []
    for number, row in _rows(payload).items():
        provenance = row["provenance"]
        associations.append([number, provenance["source_location"], provenance["reference_unit"]])
        labels = {col: label for label, col in json.loads(provenance["columns"]).items()}
        metadata = []
        for col in COLUMNS:
            label = labels[col]
            if label in row["resolved_values"]:
                metadata.append(
                    [
                        col,
                        provenance[f"{label}.anchor"],
                        provenance[f"{label}.merged_range"],
                        row["resolved_values"][label],
                    ]
                )
        merges.append([number, metadata])
    assert _digest(associations) == ASSOCIATION_SHA256
    assert _digest(merges) == MERGES_SHA256


def test_bundled_output_and_native_reload_preserve_all_source_tuples(payload: dict[str, Any]) -> None:
    assert json.loads(CATALOG.read_text(encoding="utf-8")) == payload
    catalog = load_evidentia_catalog(CATALOG)
    loaded = catalog.model_dump(mode="json")
    assert _digest(_physical_rows(_rows(loaded))) == PHYSICAL_ROWS_SHA256
    assert catalog.control_count == 324
    assert len(catalog.statement_rows()) == 324
    assert len(catalog.families) == 27
    assert Counter(c.properties["source_unit_kind"] for c in catalog.controls) == {
        "control": 176,
        "enhancement": 118,
        "section": 30,
    }
    source_free = copy.deepcopy(payload)
    for control in source_free["controls"]:
        control["source_rows"] = []
    without_rows = ControlCatalog.model_validate(source_free)
    analyzer = GapAnalyzer()
    assert list(analyzer._build_required_set({catalog.framework_id: catalog})) == list(
        analyzer._build_required_set({without_rows.framework_id: without_rows})
    )
    assert catalog.statement_rows() == without_rows.statement_rows()
    assert catalog.text_depth == without_rows.text_depth


def test_structural_ancestors_and_cso_clauses_never_become_extra_controls(payload: dict[str, Any]) -> None:
    catalog = ControlCatalog.model_validate(payload)
    assert catalog.get_control("3.2.2") is not None
    for identifier in ("1", "3", "3.2", "4", "5", "5.20.1", "5.20.1.2", "5.20.4", "5.20.7", "AC", "AT"):
        assert catalog.get_control(identifier) is None
    for identifier in ("3.2.2(1)", "3.2.2(2)", "3.2.2(3)", "IA-5(1)(a)", "IA-5(1)(e)"):
        assert catalog.get_control(identifier) is None
    cso = catalog.get_control("3.2.2")
    assert cso is not None
    assert {r.interpreted_id for r in cso.source_rows} == {"3.2.2", "3.2.2(1)", "3.2.2(2)", "3.2.2(3)"}
    assert all(r.provenance["reference_unit"] == "3.2.2" for r in cso.source_rows)
    assert "CJA" in cso.description


def test_approved_interpretations_preserve_physical_blanks_numeric_format_and_raw_titles(
    payload: dict[str, Any],
) -> None:
    rows = _rows(payload)
    for number in range(233, 265):
        row = rows[number]
        assert row["source_id"] is None and row["values"][LOCATION] is None
        assert row["resolved_values"][LOCATION] is None
        assert row["interpreted_id"] == "AT-3"
        assert row["provenance"][f"{LOCATION}.anchor"] == "R233"
        assert row["provenance"][f"{LOCATION}.merged_range"] == "R233:R264"
        assert "Reviewed AT-3" in row["provenance"]["location_basis"]
    numeric = rows[1461]
    assert type(numeric["source_id"]) is float and numeric["source_id"] == 5.2
    assert numeric["source_id_format"] == "0.00" and numeric["interpreted_id"] == "5.20"
    assert rows[1462]["source_id"] is None
    assert rows[1462]["resolved_values"][LOCATION] == 5.2
    controls = {c["id"]: c for c in payload["controls"]}
    assert "Secrurity" in rows[40]["values"]["Title"]
    assert controls["3.2.8"]["title"] == "CJIS Systems Agency Information Security Officer (CSA ISO)"
    assert rows[1312]["values"]["Title"].startswith("(1)(3)")
    assert controls["SA-15(3)"]["title"] == "DEVELOPMENT PROCESS, STANDARDS, AND TOOLS |CRITICALITY ANALYSIS"
    assert controls["IA-7"]["title"] == "Cryptographic Module Authentication"
    assert (
        controls["IR-7(1)"]["title"]
        == "INCIDENT RESPONSE ASSISTANCE | AUTOMATION SUPPORT FOR AVAILABILITY OF INFORMATION AND SUPPORT"
    )
    assert rows[955]["source_id"] == "IR-7 (1)" and rows[955]["interpreted_id"] == "IR-7(1)"


def test_independent_audit_priority_and_cloud_values_include_all_unknowns(payload: dict[str, Any]) -> None:
    rows = _rows(payload)

    def effective(row: dict[str, Any], key: str) -> Any:
        return row["resolved_values"].get(key, row["values"][key])

    pairs = Counter((effective(row, "Audit / Sanction Date"), effective(row, "Priority")) for row in rows.values())
    assert pairs == {
        ("Existing", "Existing"): 168,
        ("Zero-cycle", "P2"): 471,
        ("Existing", "P1"): 101,
        ("2024-10-01T00:00:00", "P1"): 324,
        ("Existing", "P3"): 26,
        ("Existing", "P2"): 274,
        ("Existing", "P4"): 7,
        ("Zero-cycle", "P3"): 94,
        ("Zero-cycle", "P4"): 31,
        (None, None): 4,
        ("2024-12-27T00:00:00", "P1"): 33,
    }
    assert [n for n, r in rows.items() if effective(r, "Priority") is None] == [232, 277, 871, 904]
    for number in (232, 277, 871, 904):
        assert effective(rows[number], "Audit / Sanction Date") is None
    assert effective(rows[83], "Audit / Sanction Date") == "Existing"
    assert effective(rows[89], "Audit / Sanction Date") == "2024-10-01T00:00:00"
    assert effective(rows[83], "Priority") == effective(rows[89], "Priority") == "P1"
    assert {k: effective(rows[83], k) for k in ("IaaS", "PaaS", "SaaS")} == {
        "IaaS": "Agency",
        "PaaS": "Both",
        "SaaS": "Both",
    }
    assert "IaaS=W2, PaaS=X2, SaaS=Y2; parent W1:Y1" in rows[83]["provenance"]["cloud_header"]
    controls = {c["id"]: c for c in payload["controls"]}
    assert controls["AC-2"]["properties"]["audit_sanction_state"] == "mixed"
    assert json.loads(controls["AC-2"]["properties"]["audit_sanction_source_values"]) == [
        "Existing",
        "2024-10-01T00:00:00",
    ]
    assert controls["AT-3"]["priority"] is None
    assert controls["AT-3"]["properties"]["priority_state"] == "mixed-with-unknown"


def test_ordered_context_roles_alternatives_tables_and_exceptions_are_retained(payload: dict[str, Any]) -> None:
    controls = {c["id"]: c for c in payload["controls"]}
    for control in controls.values():
        assert control["description"] == "\n\n".join(r["values"][STATEMENT] for r in control["source_rows"])
        assert "entity" in control["properties"]["applicability"]
    assert "FBI CJIS Division ISO only" in controls["3.2.10"]["guidance"]
    assert "alternatives, not cumulative obligations" in controls["5.20.1.4"]["guidance"]
    assert [r["row"] for r in controls["5.20.1.4"]["source_rows"]] == list(range(1489, 1497))
    assert "MDM" in controls["5.20.1.4"]["description"]
    assert "exception" in controls["5.20.7.2"]["guidance"]
    assert "optional path" in controls["5.20.7.2.1"]["guidance"]
    assert "Attribute Name" in controls["AC-2"]["description"]
    assert all(n in {r["row"] for r in controls["IA-5(1)"]["source_rows"]} for n in (714, 739, 754, 779, 800))
    assert [c["ordering"] for c in payload["controls"]] == sorted(c["ordering"] for c in payload["controls"])


@pytest.mark.parametrize(
    "number,raw,annotation",
    [
        (1464, "pre-80.11i", "pre-802.11i"),
        (1514, "5.20.8.1", "5.20.7.1"),
        (1529, "Section 5.3 Incident Response", "without claiming a verified correction"),
    ],
)
def test_source_differences_are_annotated_without_rewriting(
    number: int, raw: str, annotation: str, payload: dict[str, Any]
) -> None:
    row = _rows(payload)[number]
    assert raw in row["values"][STATEMENT]
    assert annotation in row["provenance"]["source_annotation"]
    assert row["provenance"]["annotation_source"].endswith("cjis_security_policy_v6-1_20260625-1.pdf")


def test_publication_scope_and_authority_specific_audit_context(payload: dict[str, Any]) -> None:
    catalog = ControlCatalog.model_validate(payload)
    assert "Companion" in catalog.framework_name and catalog.version == "6.1"
    assert "2026-06-25" in catalog.notes
    assert "not an official FBI requirement count" in catalog.notes
    assert "Full policy prose" in catalog.notes and "outside" in catalog.notes
    assert "automatic applicability determination" in catalog.notes
    assert set(catalog.audit_contexts) == {"US-TX"}
    texas = catalog.audit_contexts["US-TX"]
    assert texas.version == "5.9.5" and texas.valid_through == date(2027, 3, 31)
    assert "unknown" in texas.notes
    assert "third-party" in catalog.license_terms and "seals or logos" in catalog.license_terms


@pytest.mark.parametrize(
    "case",
    [
        "hash",
        "size",
        "schema",
        "version",
        "date",
        "sheet",
        "shape",
        "columns",
        "header",
        "cloud-leaf",
        "cloud-parent",
        "duplicate-row",
        "bool-row",
        "missing-row",
        "reorder-row",
        "duplicate-id",
        "normalized-collision",
        "double-assignment",
        "at3-blank",
        "at3-merge",
        "numeric-value",
        "numeric-format",
        "numeric-merge",
        "title-csa",
        "title-sa",
        "source-difference",
        "clause-group",
        "cell-loss",
        "arbitrary-cell",
        "nonfinite",
    ],
)
def test_unreviewed_source_changes_fail_closed(case: str, projection: dict[str, Any], generator: Any) -> None:
    data = copy.deepcopy(projection)
    rows = {r["row"]: r for r in data["rows"]}
    if case in {"hash", "size", "schema", "version", "date", "sheet", "shape", "columns"}:
        key, value = {
            "hash": ("source_sha256", "0" * 64),
            "size": ("source_bytes", 1),
            "schema": ("schema", "next"),
            "version": ("version", "6.2"),
            "date": ("published_on", "2026-07-23"),
            "sheet": ("sheet", "next"),
            "shape": ("dimensions", [1557, 25]),
            "columns": ("columns", list(reversed(COLUMNS))),
        }[case]
        data[key] = value
    elif case == "header":
        data["headers"][0]["cells"]["R"][0] = "Title"
    elif case == "cloud-leaf":
        data["headers"][1]["cells"]["X"][0] = "SaaS"
    elif case in {"cloud-parent", "at3-merge", "numeric-merge"}:
        data["merges"].remove({"cloud-parent": "W1:Y1", "at3-merge": "R233:R264", "numeric-merge": "R1461:R1463"}[case])
    elif case == "duplicate-row":
        data["rows"][1] = data["rows"][0]
    elif case == "bool-row":
        data["rows"][0]["row"] = True
    elif case == "missing-row":
        data["rows"].pop()
    elif case == "reorder-row":
        data["rows"][0], data["rows"][1] = data["rows"][1], data["rows"][0]
    elif case in {"duplicate-id", "normalized-collision"}:
        data["locations"][1]["id"] = (
            data["locations"][0]["id"] if case == "duplicate-id" else " " + data["locations"][0]["id"].lower() + " "
        )
    elif case == "double-assignment":
        data["locations"][1]["rows"].append(data["locations"][0]["rows"][0])
    elif case == "at3-blank":
        rows[233]["cells"]["R"][0] = "AT-4"
    elif case in {"numeric-value", "numeric-format"}:
        rows[1461]["cells"]["R"][0 if case == "numeric-value" else 2] = "5.20" if case == "numeric-value" else "General"
    elif case in {"title-csa", "title-sa"}:
        rows[40 if case == "title-csa" else 1312]["cells"]["S"][0] = "changed"
    elif case == "source-difference":
        rows[1514]["cells"]["T"][0] = "changed"
    elif case == "clause-group":
        next(s for s in data["reviewed_scopes"] if s["location"] == "3.2.2(1)")["reference_unit"] = "3.2.2(1)"
    elif case == "cell-loss":
        del rows[4]["cells"]["B"]
    elif case == "arbitrary-cell":
        rows[83]["cells"]["W"][0] = "Both"
    elif case == "nonfinite":
        rows[4]["cells"]["B"][0] = float("nan")
    with pytest.raises(ValueError):
        generator.build_catalog(data)


def test_duplicate_json_keys_are_rejected_before_loss(tmp_path: Path, generator: Any) -> None:
    source = tmp_path / "duplicate.json"
    source.write_text('{"version":"6.1","version":"6.2"}', encoding="ascii", newline="\n")
    with pytest.raises(ValueError, match="Duplicate JSON object key"):
        generator.read_source(source)


def test_explicit_generation_is_deterministic_isolated_and_crlf_independent(tmp_path: Path, generator: Any) -> None:
    isolated_source = tmp_path / "source.json"
    isolated_source.write_bytes(SOURCE.read_bytes().replace(b"\r\n", b"\n").replace(b"\n", b"\r\n"))
    output = tmp_path / "output/cjis.json"
    assert generator.main(["--source", str(isolated_source), "--output", str(output)]) == 0
    expected = CATALOG.read_bytes().replace(b"\r\n", b"\n")
    assert output.read_bytes() == expected
    assert b"\r" not in output.read_bytes()
    assert generator.generate(isolated_source, output) == output
    assert output.read_bytes() == expected
    assert sorted(p.relative_to(tmp_path).as_posix() for p in tmp_path.rglob("*.json")) == [
        "output/cjis.json",
        "source.json",
    ]


def test_failed_source_validation_does_not_create_or_overwrite_output(tmp_path: Path, generator: Any) -> None:
    bad = tmp_path / "bad.json"
    bad.write_text('{"schema":"unreviewed"}', encoding="ascii", newline="\n")
    output = tmp_path / "catalog.json"
    with pytest.raises(ValueError):
        generator.generate(bad, output)
    assert not output.exists()
    output.write_text("retained", encoding="ascii", newline="\n")
    with pytest.raises(ValueError):
        generator.generate(bad, output)
    assert output.read_text() == "retained"


def test_import_does_not_write_files(tmp_path: Path) -> None:
    code = (
        "import importlib.util,pathlib; "
        "pathlib.Path.write_text=lambda *a,**k: (_ for _ in ()).throw(AssertionError('import write')); "
        f"s=importlib.util.spec_from_file_location('cjis_no_write',{str(GENERATOR)!r}); "
        "m=importlib.util.module_from_spec(s); s.loader.exec_module(m)"
    )
    subprocess.run([sys.executable, "-B", "-c", code], cwd=tmp_path, check=True, capture_output=True)
    assert not list(tmp_path.iterdir())


@pytest.mark.parametrize("state,expected", [("matching", 0), ("crlf", 0), ("drifted", 1), ("missing", 1)])
def test_check_mode_compares_without_creating_or_changing_files(
    state: str, expected: int, tmp_path: Path, generator: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    output = tmp_path / "checked.json"
    data = CATALOG.read_bytes().replace(b"\r\n", b"\n")
    if state != "missing":
        output.write_bytes(
            data.replace(b"\n", b"\r\n") if state == "crlf" else b"changed" if state == "drifted" else data
        )
    before = output.read_bytes() if output.exists() else None

    def reject_write(*args: Any, **kwargs: Any) -> None:
        raise AssertionError("--check must not write")

    monkeypatch.setattr(Path, "write_text", reject_write)
    monkeypatch.setattr(Path, "write_bytes", reject_write)
    assert generator.main(["--source", str(SOURCE), "--output", str(output), "--check"]) == expected
    assert (output.read_bytes() if output.exists() else None) == before


@pytest.mark.parametrize("alias", ["same-path", "hard-link"])
def test_generation_never_overwrites_source_through_file_aliases(alias: str, tmp_path: Path, generator: Any) -> None:
    source = tmp_path / "source.json"
    source.write_bytes(SOURCE.read_bytes())
    output = source
    if alias == "hard-link":
        output = tmp_path / "alias.json"
        output.hardlink_to(source)
        assert output.samefile(source)
    original = source.read_bytes()
    with pytest.raises(ValueError, match="same file"):
        generator.generate(source, output)
    assert source.read_bytes() == output.read_bytes() == original
