"""Generate the existing article summaries with scoped, source-verified application dates.

This is an editorial summary catalog, not a full consolidation of the amended Act.
Regulation (EU) 2026/1744 Article 1(40) amends Article 113's application schedule.
"""

import json
from pathlib import Path

import _generators

SOURCE = "https://eur-lex.europa.eu/eli/reg/2026/1744/oj/eng"
ORIGINAL_SCHEDULE = "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-113"
FRIA_SCOPE = "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-27"

ROWS = [
    (
        "AIA.Art.5",
        "Prohibited AI practices",
        (
            "Prohibited AI practices (social scoring by public authorities, real-time biometric "
            "identification in public spaces, subliminal manipulation, exploitation of "
            "vulnerabilities, untargeted facial scraping, emotion inference in "
            "workplace/education)."
        ),
        "Prohibitions",
        "unacceptable",
        None,
    ),
    (
        "AIA.Art.6",
        "Classification rules for high-risk AI systems",
        (
            "Classification of AI systems as high-risk under Annex III, plus exemptions for "
            "systems performing narrow procedural tasks, preparatory work, or detection of "
            "decision patterns."
        ),
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.9",
        "Risk management system",
        "Risk management system established, implemented, documented, and maintained across the AI system lifecycle.",
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.10",
        "Data and data governance",
        (
            "Training, validation, and testing datasets meet quality criteria (relevance, "
            "representativeness, appropriate statistical properties, absence of errors)."
        ),
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.11",
        "Technical documentation",
        (
            "Technical documentation drawn up before the high-risk AI system is placed on the "
            "market or put into service; kept up to date."
        ),
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.12",
        "Record-keeping (logs)",
        "Automatic recording of events ('logs') over the lifecycle of the high-risk AI system to ensure traceability.",
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.13",
        "Transparency and provision of information to deployers",
        (
            "Design and development such that operation is sufficiently transparent to enable "
            "deployers to interpret outputs and use appropriately."
        ),
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.14",
        "Human oversight",
        "Effective human oversight by natural persons during the period of use; tools enabling the oversight built in.",
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.15",
        "Accuracy, robustness and cybersecurity",
        (
            "Design and development to achieve appropriate level of accuracy, robustness, and "
            "cybersecurity over the lifecycle; resilience to errors, faults, inconsistencies, and "
            "attempts to alter inputs/outputs."
        ),
        "High-Risk AI Systems",
        "high",
        "all",
    ),
    (
        "AIA.Art.16",
        "Obligations of providers of high-risk AI systems",
        (
            "Providers' obligations: compliance, QMS, documentation, automatic logs, conformity "
            "assessment, registration in EU database, post-market monitoring."
        ),
        "High-Risk AI Systems",
        "high",
        None,
    ),
    (
        "AIA.Art.17",
        "Quality management system",
        "Quality management system in place ensuring compliance; documented in written form.",
        "High-Risk AI Systems",
        "high",
        None,
    ),
    (
        "AIA.Art.18",
        "Documentation keeping",
        (
            "Documentation kept at disposal of national competent authorities for 10 years after "
            "the system is placed on the market."
        ),
        "High-Risk AI Systems",
        "high",
        None,
    ),
    (
        "AIA.Art.19",
        "Automatically generated logs",
        (
            "Logs automatically generated by the high-risk AI system kept by the provider for an "
            "appropriate period (>= 6 months)."
        ),
        "High-Risk AI Systems",
        "high",
        None,
    ),
    (
        "AIA.Art.26",
        "Obligations of deployers of high-risk AI systems",
        (
            "Deployers' use of the system in accordance with provider's instructions, oversight, "
            "input data quality, log retention, registry checks."
        ),
        "Deployer Obligations",
        "high",
        None,
    ),
    (
        "AIA.Art.27",
        "Fundamental rights impact assessment (FRIA)",
        (
            "Public-sector deployers and certain private deployers of Annex III systems conduct a "
            "fundamental rights impact assessment before deployment."
        ),
        "Deployer Obligations",
        "high",
        None,
    ),
    (
        "AIA.Art.50",
        "Transparency obligations for providers and deployers of certain AI systems",
        (
            "Disclosure to natural persons interacting with AI systems (50.1), notification of "
            "emotion recognition (50.3), labelling of synthetic/deepfake content (50.4)."
        ),
        "Transparency",
        "limited",
        None,
    ),
    (
        "AIA.Art.51",
        "Classification of general-purpose AI models as GPAI models with systemic risk",
        (
            "GPAI models exceeding compute threshold (10^25 FLOPs) presumed to have systemic risk;"
            " Commission may designate others."
        ),
        "GPAI",
        "high",
        None,
    ),
    (
        "AIA.Art.53",
        "Obligations for providers of general-purpose AI models",
        "GPAI providers: technical documentation, copyright policy, training-data summary, downstream-provider info.",
        "GPAI",
        "limited",
        None,
    ),
    (
        "AIA.Art.55",
        "Obligations for providers of general-purpose AI models with systemic risk",
        (
            "Additional obligations for systemic-risk GPAI: model evaluation, adversarial testing,"
            " risk assessment + mitigation, incident reporting, cybersecurity."
        ),
        "GPAI",
        "high",
        None,
    ),
    (
        "AIA.Art.72",
        "Post-market monitoring system",
        "Providers establish and document a post-market monitoring system proportionate to risks.",
        "Post-Market",
        "high",
        None,
    ),
    (
        "AIA.Art.73",
        "Reporting of serious incidents",
        (
            "Providers report serious incidents to market surveillance authorities of Member "
            "States within set deadlines (15 days; 2 days for widespread infringement; 10 days for"
            " serious + irreversible disruption)."
        ),
        "Post-Market",
        "high",
        None,
    ),
    (
        "AIA.Art.99",
        "Penalties",
        (
            "Administrative fines up to EUR 35M or 7% of total worldwide annual turnover for "
            "Article 5 violations; lower tiers for other infringements."
        ),
        "Penalties",
        "informational",
        None,
    ),
]

RISK_CATEGORIES = [
    "biometrics",
    "critical_infrastructure",
    "education",
    "employment",
    "essential_services",
    "law_enforcement",
    "migration",
    "justice",
]
LEGACY_NOTE = (
    "Tier bumped D -> A (article-level text matches the authoritative regulation). Annex "
    "III risk-category annotations added per v0.9.3 P2.1. Sub-article granularity deferred"
    " to v0.9.4 SME pass."
)


def build_catalog() -> dict:
    """Keep summaries and risk annotations while separating the amended dates by scope."""
    controls = []
    for control_id, title, description, family, risk, annex in ROWS:
        control = {"id": control_id, "title": title, "description": description, "family": family}
        if risk is not None:
            control["risk_tier"] = risk
        if annex is not None:
            control["applies_to_annex_iii"] = annex
        article = int(control_id.rsplit(".", 1)[1])
        props = {
            "date_source_url": SOURCE,
            "original_schedule_source_url": ORIGINAL_SCHEDULE,
            "scope_note": (
                "Dates are source metadata, not automatic applicability decisions. Article 111 and the"
                " relevant system, role and exemptions still need review."
            ),
        }
        if article in {6, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 26, 27}:
            props["annex_iii_application_on"] = "2027-12-02"
            if article == 27:
                props["scope_source_url"] = FRIA_SCOPE
                props["scope_note"] = (
                    "Article 27(1) concerns Article 6(2) systems, excluding Annex III point 2. "
                    "It covers deployers that are public-law bodies, private entities providing public "
                    "services, and deployers under Annex III points 5(b) and 5(c). No Annex I date "
                    "is assigned. Other scope and transition conditions still require review."
                )
            else:
                props["annex_i_application_on"] = "2028-08-02"
            if article == 6:
                props["article_6_5_application_on"] = "2026-08-02"
        elif article == 5:
            props.update(
                {
                    "application_on": "2025-02-02",
                    "new_prohibitions_application_on": "2026-12-02",
                    "new_prohibitions_scope": (
                        "Article 5(1)(ba), 5(1)(bb), 5(1a) and 5(1b). The summary is not a full text consolidation."
                    ),
                }
            )
        elif article in {51, 53, 55, 99}:
            props["application_on"] = "2025-08-02"
        else:
            props["application_on"] = "2026-08-02"
        control["properties"] = props
        controls.append(control)
    return {
        "framework_id": "eu-ai-act",
        "framework_name": "EU AI Act (Regulation 2024/1689)",
        "version": "2024/1689; application dates amended by 2026/1744",
        "source": SOURCE,
        "tier": "A",
        "category": "control",
        "placeholder": False,
        "v0_9_3_note": LEGACY_NOTE,
        "families": list(dict.fromkeys(row[3] for row in ROWS)),
        "annex_iii_risk_categories": RISK_CATEGORIES,
        "controls": controls,
        "verified_on": "2026-09-09",
        "notes": (
            "Article-level editorial summaries, not verbatim law or a full consolidation. "
            "Applicability dates were checked against enacted Regulation (EU) 2026/1744, published"
            " 2026-07-24 and in force 2026-07-27. Chapter III Sections 1-3, except Article 6(5), "
            "apply from 2027-12-02 for Annex III systems and 2028-08-02 for Annex I systems where "
            "the provision applies. Article 27(1) has its own Annex III and deployer limits. The "
            "general date remains 2026-08-02; specified new Article 5 prohibitions apply from "
            "2026-12-02. Earlier prohibitions and GPAI provisions keep their earlier dates. Scope "
            "and transitional provisions require separate review; dates do not filter gap "
            "analysis."
        ),
    }


def main() -> Path:
    """Write only this catalog; no network access or clock-dependent output."""
    target = _generators.DATA_ROOT / "international" / "eu-ai-act.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(build_catalog(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    return target


if __name__ == "__main__":
    print(main())
