#!/usr/bin/env python3
"""Deterministic generator for the wiki "mirror" pages (D6, v0.10.7).

The Evidentia GitHub wiki (synced from ``docs/wiki/`` by
``.github/workflows/sync-wiki.yml`` -> ``scripts/sync_wiki_to_github.py``)
wants its ``6-project/`` and ``5-compliance/`` sections to MIRROR the
canonical project docs that live at the repo root / under ``docs/`` so
wiki readers see them in-context. Hand-copying drifts; this script
generates each mirror from its canonical source instead, and a
``--check`` mode detects drift (same idiom as
``scripts/catalogs/gen_osps_crosswalks.py``).

What a mirror page is
---------------------
For each of the 13 ``(canonical_source, wiki_mirror)`` mappings in
:data:`MIRRORS`, the generator:

1. Reads the canonical source verbatim.
2. Rewrites its relative links (see "Link handling" below).
3. Prepends a generated banner: an HTML-comment provenance marker plus a
   short visible blockquote that names the canonical source and says
   "do not edit this file directly".
4. Writes the result to the wiki mirror path under ``docs/wiki/``.

The canonical docs are NOT moved or deleted -- several are NORMATIVE and
referenced elsewhere (e.g. ``docs/ocsf-mapping.md`` is referenced from
external memory). The mirrors are a downstream projection only.

Link handling (absolute GitHub blob URLs)
-----------------------------------------
The canonical docs carry relative links written from THEIR location
(repo root for ``CHANGELOG.md`` etc.; ``docs/`` for ``docs/ocsf-mapping.md``
etc.). Copied verbatim into ``docs/wiki/<section>/`` those links would
resolve against the wrong base and break.

This generator rewrites every *relative* link target to an ABSOLUTE
GitHub blob URL rooted at the repo
(``https://github.com/Polycentric-Labs/evidentia/blob/main/<repo-path>``).
That single strategy is correct from all three rendering contexts:

* **In-repo / GitHub file browse + ``check_docs_health.py --strict``** --
  its ``cross_link_resolve`` check skips ``http(s)://`` targets entirely,
  so an absolute URL is never flagged as a broken in-repo link. (A
  root-relative or repo-relative path, by contrast, would resolve from
  ``docs/wiki/<section>/`` to a non-existent nested path and WARN/FAIL.)
* **GitHub wiki** -- ``scripts/sync_wiki_to_github.py``'s ``rewrite_links``
  leaves ``https://`` targets unchanged, so the mirror's absolute URLs
  survive the flat-namespace sync intact (the wiki has no repo-root or
  ``docs/`` concept to resolve a relative path against).
* **MkDocs / any other renderer** -- an absolute URL resolves the same
  everywhere.

Anchor-only (``#frag``), external (``http(s)://``, ``mailto:``,
``ftp://``) and protocol-relative (``//host``) links are passed through
untouched; a fragment on a relative link is preserved on the rewritten
absolute URL. Image links (``![alt](src)``) are left alone (the mirrors
in scope carry none; rewriting an image ``src`` to a ``/blob/`` URL would
break rendering -- raw URLs differ).

Modes
-----
``sync_mirrors.py``
    Generate / update all 13 mirror pages in place under ``docs/wiki/``.
``sync_mirrors.py --check``
    Do not write. Exit 0 if every committed mirror matches what would be
    regenerated from its canonical source; exit 1 + print which mirrors
    drifted. (CI / pre-tag drift gate; wired into ``sync-wiki.yml`` so a
    push always refreshes the mirrors before the wiki push.)

Per the publishing-authority protocol (~/.claude/CLAUDE.md), this script
NEVER pushes, tags, or publishes. It only reads canonical docs + writes
the in-tree wiki mirror files.
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# scripts/wiki/sync_mirrors.py -> repo root is two parents up.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Canonical blob-URL base for absolute-link rewriting. Matches the base
# used by scripts/sync_wiki_to_github.py (which defaults the repo to
# Polycentric-Labs/evidentia). Kept as a module constant so the link
# rewriter is a pure function the tests can drive with a fixture base.
BLOB_URL_BASE = "https://github.com/Polycentric-Labs/evidentia/blob/main"


@dataclass(frozen=True)
class Mirror:
    """One canonical-source -> wiki-mirror mapping.

    ``source`` and ``mirror`` are repo-root-relative POSIX paths. ``source``
    is the canonical doc (left in place); ``mirror`` is the generated wiki
    page under ``docs/wiki/<section>/``.
    """

    source: str
    mirror: str


# The 13 mirror mappings (canonical source -> generated wiki mirror).
# 6-project (9) + 5-compliance (4). Order is the order the index pages
# list them, for a readable default-mode log.
MIRRORS: tuple[Mirror, ...] = (
    # --- 6-project (9) ---
    Mirror("docs/ROADMAP.md", "docs/wiki/6-project/roadmap.md"),
    Mirror("CHANGELOG.md", "docs/wiki/6-project/changelog.md"),
    Mirror("docs/api-stability.md", "docs/wiki/6-project/api-stability.md"),
    Mirror("docs/deprecation-calendar.md", "docs/wiki/6-project/deprecation-policy.md"),
    Mirror("GOVERNANCE.md", "docs/wiki/6-project/governance.md"),
    Mirror("SECURITY.md", "docs/wiki/6-project/security.md"),
    Mirror("CONTRIBUTING.md", "docs/wiki/6-project/contributing.md"),
    Mirror("EOL.md", "docs/wiki/6-project/eol.md"),
    Mirror("docs/verification.md", "docs/wiki/6-project/verification.md"),
    # --- 5-compliance (4) ---
    Mirror("docs/ocsf-mapping.md", "docs/wiki/5-compliance/ocsf-mapping.md"),
    Mirror("docs/gemara-mapping.md", "docs/wiki/5-compliance/gemara-mapping.md"),
    Mirror(
        "docs/financial-sector-overlay.md",
        "docs/wiki/5-compliance/financial-sector-overlay.md",
    ),
    Mirror(
        "docs/contributing-a-catalog.md",
        "docs/wiki/5-compliance/contributing-a-catalog.md",
    ),
)

# Markdown link matcher. The leading ``(?<!\!)`` excludes image links
# (``![alt](src)``) so their src is never rewritten to a /blob/ URL.
_LINK_RE = re.compile(r"(?<!\!)\[([^\]\n]+)\]\(([^)\n]+)\)")

# Targets passed through untouched: anchors, external schemes, and
# protocol-relative (``//host/...``) links.
_PASSTHROUGH_PREFIXES = ("#", "http://", "https://", "mailto:", "ftp://", "//")


# ---------------------------------------------------------------------------
# Pure functions (no I/O -- unit-tested directly).
# ---------------------------------------------------------------------------


def rewrite_links(content: str, source_rel: str, blob_base: str = BLOB_URL_BASE) -> str:
    """Rewrite relative markdown links to absolute GitHub blob URLs.

    ``source_rel`` is the canonical doc's repo-root-relative POSIX path
    (e.g. ``docs/ocsf-mapping.md`` or ``CHANGELOG.md``); relative link
    targets are resolved against its *parent* directory and re-expressed
    as ``<blob_base>/<repo-relative-path>``.

    Anchor-only / external / protocol-relative links are returned
    unchanged. A ``#fragment`` on a relative link is preserved on the
    rewritten URL. Targets that escape the repo root (excess ``../``) are
    left unchanged rather than producing an out-of-repo blob URL.

    Pure: no filesystem access (it does NOT check whether the target
    exists -- that is the canonical doc's own concern, already covered by
    ``check_docs_health.py`` running on the canonical source).
    """
    source_dir = Path(source_rel).parent

    def replace(match: re.Match[str]) -> str:
        text = match.group(1)
        target = match.group(2).strip()

        if target.startswith(_PASSTHROUGH_PREFIXES):
            return match.group(0)

        if "#" in target:
            path_part, frag = target.split("#", 1)
            anchor = f"#{frag}"
        else:
            path_part, anchor = target, ""

        if not path_part:
            # Pure ``#anchor`` already handled above; an empty path with a
            # trailing-stripped fragment shouldn't occur, but pass through.
            return match.group(0)

        # Resolve the relative target against the canonical doc's dir,
        # then collapse ``.`` / ``..`` segments lexically (no filesystem
        # access -- posixpath.normpath is purely textual).
        combined = (source_dir / path_part).as_posix()
        repo_path = posixpath.normpath(combined)

        # If normalization escaped the repo root (leading ``..``) or
        # produced an absolute path, leave the link untouched -- we cannot
        # form a valid in-repo blob URL from it.
        if repo_path.startswith("..") or repo_path.startswith("/"):
            return match.group(0)

        return f"[{text}]({blob_base}/{repo_path}{anchor})"

    return _LINK_RE.sub(replace, content)


def build_banner(source_rel: str) -> str:
    """Build the auto-generated header banner for a mirror page.

    Combines an HTML-comment provenance marker (machine-detectable, does
    not render) with a short visible blockquote that names the canonical
    source and tells editors to edit the source + re-run this script.
    """
    return (
        f"<!-- AUTO-GENERATED MIRROR of {source_rel} "
        f"-- do not edit directly -->\n"
        f"> **Auto-generated mirror.** This page mirrors "
        f"[`{source_rel}`]({BLOB_URL_BASE}/{source_rel}), the canonical "
        f"source of truth. Do not edit this file directly; edit "
        f"`{source_rel}` and re-run `scripts/wiki/sync_mirrors.py`.\n\n"
    )


def render_mirror(content: str, source_rel: str, blob_base: str = BLOB_URL_BASE) -> str:
    """Render a full mirror page from a canonical source's content.

    Prepends the banner, then appends the link-rewritten body. Pure (no
    I/O): the in-memory transform the ``--check`` mode compares against
    the committed file.
    """
    return build_banner(source_rel) + rewrite_links(content, source_rel, blob_base)


# ---------------------------------------------------------------------------
# I/O helpers.
# ---------------------------------------------------------------------------


def generate_all(repo_root: Path = REPO_ROOT) -> dict[str, str]:
    """Render every mirror; return ``{mirror_rel_path: rendered_text}``.

    Reads each canonical source under ``repo_root``. Raises
    ``FileNotFoundError`` if a canonical source is missing (a mapping
    referencing a deleted/renamed doc is a bug to surface, not swallow).
    """
    out: dict[str, str] = {}
    for m in MIRRORS:
        source_path = repo_root / m.source
        content = source_path.read_text(encoding="utf-8")
        out[m.mirror] = render_mirror(content, m.source)
    return out


def compare(rendered: dict[str, str], repo_root: Path = REPO_ROOT) -> list[str]:
    """Compare rendered mirrors against the committed files on disk.

    ``rendered`` is ``{mirror_rel_path: rendered_text}`` (the output of
    :func:`generate_all`). Returns an ordered list of per-file drift
    summaries; an empty list means every mirror matches its committed
    copy byte-for-byte. Pure read-only (no writes, no network).
    """
    drift: list[str] = []
    for mirror_rel, content in sorted(rendered.items()):
        committed_path = repo_root / mirror_rel
        if not committed_path.exists():
            drift.append(f"  {mirror_rel}: committed mirror missing")
            continue
        committed = committed_path.read_text(encoding="utf-8")
        if committed != content:
            drift.append(_diff_summary(committed, content, mirror_rel))
    return drift


def _diff_summary(expected: str, actual: str, name: str) -> str:
    """Return a short first-divergence summary between two text blobs."""
    exp_lines = expected.splitlines()
    act_lines = actual.splitlines()
    # strict=False: intentionally compare the common prefix; a length
    # mismatch is reported separately below.
    for i, (exp, act) in enumerate(zip(exp_lines, act_lines, strict=False)):
        if exp != act:
            return (
                f"  {name}: first diff at line {i + 1}\n"
                f"    committed:   {exp!r}\n"
                f"    regenerated: {act!r}"
            )
    if len(exp_lines) != len(act_lines):
        return (
            f"  {name}: line-count differs "
            f"(committed={len(exp_lines)}, regenerated={len(act_lines)})"
        )
    return f"  {name}: content differs only in trailing bytes / EOL"


# ---------------------------------------------------------------------------
# CLI.
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Do not write. Exit 0 if every committed mirror matches what "
            "would be regenerated from its canonical source; exit 1 + "
            "print a drift summary on divergence. (CI / pre-tag gate.)"
        ),
    )
    args = parser.parse_args(argv)

    try:
        rendered = generate_all()
    except FileNotFoundError as exc:
        print(f"ERROR: canonical source missing: {exc}", file=sys.stderr)
        return 2

    if args.check:
        drift = compare(rendered)
        if drift:
            print(
                "DRIFT: committed wiki mirrors differ from their canonical "
                "sources:",
                file=sys.stderr,
            )
            for line in drift:
                print(line, file=sys.stderr)
            print(
                "\nRe-run `scripts/wiki/sync_mirrors.py` (no --check) to "
                "regenerate the mirrors from canonical, then commit.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: all {len(rendered)} wiki mirrors match their canonical sources.")
        return 0

    for mirror_rel, content in rendered.items():
        out_path = REPO_ROOT / mirror_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding="utf-8")
        print(f"  wrote {mirror_rel}")
    print(f"Generated {len(rendered)} wiki mirror pages from canonical sources.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
