"""Regenerate a receipt-bound FedRAMP snapshot from explicit local tuples.

Run with python -m scripts.registries.refresh_fedramp. The input is one complete
reviewed tuple file and the receipt is the reviewed public source index. --check
compares regenerated bytes to an existing output without creating or writing files.
The shared file boundary also serves the CMVP and FCC offline converters.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import tempfile
from collections.abc import Callable
from datetime import datetime
from decimal import DecimalException
from pathlib import Path
from typing import Any, cast

from evidentia_collectors.enterprise_retention._parsing import _wire_depth
from evidentia_collectors.registries import fedramp
from evidentia_collectors.registries._contracts import ProductTarget, normalized_source_time
from evidentia_collectors.registries._snapshots import _decode_gzip, canonical_gzip
from evidentia_collectors.registries._source_fields import _TABLE_SHA256
from evidentia_collectors.retention import _parsing as scalar
from pydantic import JsonValue

MAX_BYTES = 16_777_216
MAX_NODES = 1_000_000
MAX_RECORDS = 50_000
_SOURCE_KEYS = {"source_id", "capture_name", "url", "raw_sha256", "raw_bytes", "retrieval", "source_cutoff"}
_ROOT_KEYS = {
    "schema_version",
    "registry",
    "source_kind",
    "sources",
    "tables",
    "selected_occurrence_counts",
    "representation",
}
_PATHS = {"products": "/data/Products", "history": "/data/certprocessstatuschangelog", "packages": "/data/frc-cso-pkg"}
Regenerator = Callable[[object, dict[str, Any]], dict[str, Any]]


class RefreshError(ValueError):
    def __init__(self) -> None:
        super().__init__("invalid_offline_registry_input")


class _Scanner(scalar._JSONScanner):
    def _node(self) -> None:
        self.nodes += 1
        if self.nodes > MAX_NODES:
            raise RefreshError()


class _Budget(scalar._JSONBudget):
    def node(self) -> None:
        self.nodes += 1
        if self.nodes > MAX_NODES:
            raise RefreshError()

    def add(self, size: int) -> None:
        self.size += size
        if self.size > MAX_BYTES:
            raise RefreshError()

    def clone(self, value: object, depth: int) -> JsonValue:
        kind = type(value)
        if (
            value is not None
            and kind is not str
            and kind is not bool
            and kind is not int
            and kind is not float
            and kind is not list
            and kind is not dict
        ):
            raise RefreshError()
        if depth >= 16 and (kind is list or kind is dict):
            raise RefreshError()
        return super().clone(value, depth)


def native(value: object) -> Any:
    """Detach finite native JSON, rejecting callbacks before their invocation."""
    try:
        return _Budget().clone(value, 0)
    except (ValueError, TypeError, OverflowError, RecursionError, RuntimeError):
        raise RefreshError() from None


def parse_source(raw: bytes) -> dict[str, Any]:
    try:
        if type(raw) is not bytes or len(raw) > MAX_BYTES:
            raise RefreshError()
        text = raw.decode("utf-8", errors="strict")
        if text.startswith("\ufeff"):
            raise RefreshError()
        _wire_depth(text, max_depth=16)
        _Scanner(text).scan()
        value = json.loads(
            text,
            parse_int=scalar._integer,
            parse_float=scalar._finite_float,
            parse_constant=scalar._constant,
            object_pairs_hook=scalar._object,
        )
        return obj(native(value))
    except (ValueError, TypeError, UnicodeError, OverflowError, RecursionError, DecimalException):
        raise RefreshError() from None


def encode(value: object) -> bytes:
    try:
        result = json.dumps(
            native(value), sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
        ).encode("utf-8")
        if len(result) >= MAX_BYTES:
            raise RefreshError()
        return result + b"\n"
    except (ValueError, TypeError, UnicodeError, OverflowError, RecursionError):
        raise RefreshError() from None


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def obj(value: Any, keys: set[str] | None = None) -> dict[str, Any]:
    if type(value) is not dict or (keys is not None and set(value) != keys):
        raise RefreshError()
    return cast(dict[str, Any], value)


def rows(value: Any, *, limit: int = MAX_RECORDS) -> list[Any]:
    if type(value) is not list or len(value) > limit:
        raise RefreshError()
    return value


def text_value(value: Any) -> str:
    if type(value) is not str:
        raise RefreshError()
    return value


def count(value: Any, maximum: int = MAX_BYTES) -> int:
    if type(value) is not int or not 0 <= value <= maximum:
        raise RefreshError()
    return value


def hash_value(value: Any) -> str:
    if type(value) is not str or re.fullmatch(r"[0-9a-f]{64}", value) is None:
        raise RefreshError()
    return value


def verify_bytes(raw: bytes, binding: dict[str, Any]) -> None:
    if type(raw) is not bytes or len(raw) > MAX_BYTES:
        raise RefreshError()
    if len(raw) != count(binding.get("bytes")) or digest(raw) != hash_value(binding.get("sha256")):
        raise RefreshError()


def tuple_binding(value: object, kind: str) -> dict[str, Any]:
    binding = obj(native(value), {"bytes", "sha256", "source_kind"})
    count(binding["bytes"])
    hash_value(binding["sha256"])
    if binding["source_kind"] != kind:
        raise RefreshError()
    return binding


def _publisher_instant(value: object) -> str:
    instant = normalized_source_time(value)
    if instant is None:
        raise RefreshError()
    return instant


def source_manifest(sources: list[Any], *, registry: str) -> list[dict[str, Any]]:
    result = []
    seen: set[str] = set()
    for source in sources:
        item = obj(source, _SOURCE_KEYS | ({"commit"} if registry == "fedramp" else set()))
        source_id = text_value(item["source_id"])
        if source_id in seen:
            raise RefreshError()
        seen.add(source_id)
        for key in ("capture_name", "url"):
            text_value(item[key])
        hash_value(item["raw_sha256"])
        count(item["raw_bytes"])
        retrieval = obj(item["retrieval"], {"started_at", "finished_at"})
        for value in retrieval.values():
            if datetime.fromisoformat(text_value(value)).utcoffset() is None:
                raise RefreshError()
        cutoff = item["source_cutoff"]
        publisher = None
        if registry == "fedramp":
            cutoff = obj(cutoff, {"source_pointer", "value"})
            for value in cutoff.values():
                text_value(value)
            _publisher_instant(cutoff["value"])
            if re.fullmatch(r"[0-9a-f]{40}", text_value(item["commit"])) is None:
                raise RefreshError()
            publisher = {
                "source_path": cutoff["source_pointer"],
                "literal": cutoff["value"],
                "representation": "rfc3339",
            }
        elif cutoff is not None:
            raise RefreshError()
        result.append(
            {
                "source_id": source_id,
                "url": item["url"],
                "media_type": "application/json" if registry == "fedramp" else "text/html",
                "raw_sha256": item["raw_sha256"],
                "raw_bytes": item["raw_bytes"],
                "captured_started_at": retrieval["started_at"],
                "captured_finished_at": retrieval["finished_at"],
                "publisher_version": item.get("commit"),
                "publisher_cutoff": publisher,
                "role": "selected_query_scope",
            }
        )
    return result


def tuple_document(document: object, registry: str, table_names: tuple[str, ...]) -> dict[str, Any]:
    value = obj(native(document), _ROOT_KEYS)
    if (
        value["schema_version"] != "registry-source-tuples-v1"
        or value["registry"] != registry
        or value["source_kind"] != "reviewed-native-tuples"
    ):
        raise RefreshError()
    tables = rows(value["tables"], limit=len(table_names))
    if tuple(obj(table).get("table_id") for table in tables) != table_names:
        raise RefreshError()
    counts = obj(value["selected_occurrence_counts"], set(table_names))
    if sum(count(amount, MAX_RECORDS) for amount in counts.values()) > MAX_RECORDS:
        raise RefreshError()
    for table in tables:
        values = rows(obj(table)["rows"])
        if len(values) != counts[table["table_id"]]:
            raise RefreshError()
        for index, row in enumerate(values):
            row = obj(row, {"source_index", "fields"})
            if count(row["source_index"], MAX_RECORDS) != index:
                raise RefreshError()
    obj(value["representation"])
    return value


def package(registry: str, binding: dict[str, Any], manifest: dict[str, Any], facts: dict[str, Any]) -> dict[str, Any]:
    if sum(len(value) for value in facts.values()) > MAX_RECORDS:
        raise RefreshError()
    return {
        "schema_version": "1",
        "snapshot_format": "selected_registry_facts_v1",
        "registry": registry,
        "tuple_input": binding,
        "field_table_sha256": _TABLE_SHA256,
        "source_manifest": manifest,
        "fact_counts": {family: len(value) for family, value in facts.items()},
        "facts": facts,
    }


def _validate_fields(table_id: str, fields: object, *, closed: bool) -> dict[str, Any]:
    selected = fedramp.select_source_fields(table_id, fields)
    schema = {
        "products": fedramp.PRODUCT_FIELDS,
        "history": fedramp.HISTORY_FIELDS,
        "packages": fedramp.PACKAGE_FIELDS,
    }[table_id]
    if set(selected) != set(schema) or (closed and selected != fields):
        raise RefreshError()
    if table_id == "products":
        ProductTarget(product_id=selected["id"])
    elif table_id == "history":
        if not selected["unique_id"] or not selected["product_id"]:
            raise RefreshError()
    else:
        identification = selected["serviceIdentification"]
        if set(identification) - {"ueiNumber"} != set(fedramp.PACKAGE_FIELDS["serviceIdentification"]) - {"ueiNumber"}:
            raise RefreshError()
    return selected


def extract_source(raw: bytes, table_id: str) -> list[dict[str, Any]]:
    """Select one reviewed JSON layout; no source discovery or file writes."""
    if type(table_id) is not str or table_id not in _PATHS:
        raise RefreshError()
    document = parse_source(raw)
    name = _PATHS[table_id].split("/")[-1]
    values = rows(obj(document.get("data")).get(name))
    if table_id != "products":
        metadata = obj(document.get("metadata"))
        if count(metadata.get("total_entries"), MAX_RECORDS) != len(values):
            raise RefreshError()
    return [
        {"source_index": index, "fields": _validate_fields(table_id, item, closed=False)}
        for index, item in enumerate(values)
    ]


def regenerate(document: object, tuple_input: dict[str, Any]) -> dict[str, Any]:
    """Build all products and retain each history/package occurrence once."""
    value = tuple_document(document, "fedramp", ("products", "history", "packages"))
    binding = tuple_binding(tuple_input, "reviewed-native-tuples")
    sources = source_manifest(rows(value["sources"], limit=3), registry="fedramp")
    if [row["source_id"] for row in sources] != ["fedramp-products", "fedramp-statuses", "fedramp-packages"]:
        raise RefreshError()
    tables = value["tables"]
    for index, table in enumerate(tables):
        obj(table, {"table_id", "source_id", "source_pointer", "source_envelope", "columns", "rows"})
        name = table["table_id"]
        if table["source_id"] != sources[index]["source_id"] or table["source_pointer"] != _PATHS[name]:
            raise RefreshError()
        schema = {
            "products": fedramp.PRODUCT_FIELDS,
            "history": fedramp.HISTORY_FIELDS,
            "packages": fedramp.PACKAGE_FIELDS,
        }[name]
        columns: list[dict[str, str]] = []
        for key, kind in schema.items():
            if type(kind) is dict:
                columns.extend(
                    {"source_pointer": _PATHS[name] + "/*/" + key + "/" + sub, "native_type": "string"} for sub in kind
                )
            else:
                columns.append(
                    {
                        "source_pointer": _PATHS[name] + "/*/" + key,
                        "native_type": "boolean"
                        if kind is bool
                        else "array of strings"
                        if type(kind) is list
                        else "string",
                    }
                )
        if table["columns"] != columns:
            raise RefreshError()
        envelope = obj(table["source_envelope"])
        if name == "products":
            metadata = obj(envelope.get("meta"), {"last_change", "produced_by"})
            text_value(metadata["produced_by"])
            cutoff = metadata["last_change"]
        else:
            metadata = obj(envelope.get("metadata"), {"export_timestamp", "total_entries", "description"})
            text_value(metadata["description"])
            if count(metadata["total_entries"], MAX_RECORDS) != len(table["rows"]):
                raise RefreshError()
            cutoff = metadata["export_timestamp"]
        if cutoff != sources[index]["publisher_cutoff"]["literal"]:
            raise RefreshError()
        for row in table["rows"]:
            row["fields"] = _validate_fields(name, row["fields"], closed=True)
    products: list[dict[str, Any]] = []
    by_id: dict[str, dict[str, Any]] = {}
    for row in tables[0]["rows"]:
        identity = row["fields"]["id"]
        if identity in by_id:
            raise RefreshError()
        output = {**row, "history": [], "package_rows": []}
        products.append(output)
        by_id[identity] = output
    history_ids: set[str] = set()
    unmatched = []
    for row in tables[1]["rows"]:
        identity = row["fields"]["unique_id"]
        if identity in history_ids:
            raise RefreshError()
        history_ids.add(identity)
        product_id = row["fields"]["product_id"]
        if product_id in by_id:
            by_id[product_id]["history"].append(row)
        else:
            unmatched.append(row)
    agreeing: set[str] = set()
    unjoined = []
    for row in tables[2]["rows"]:
        fields = row["fields"]
        expected = fields["ZD_frid_retro"]
        reasons = []
        if fields["serviceIdentification"]["fedRampPackageId"] != expected:
            reasons.append("source_ids_disagree")
        if fields["id_matches_expected"] is not True:
            reasons.append("source_agreement_flag_not_true")
        if expected not in by_id:
            reasons.append("administrative_id_not_in_product_snapshot")
        if reasons:
            unjoined.append({**row, "join_not_established": reasons})
        elif expected in agreeing:
            # A new ambiguous relation requires a reviewed source decision.
            raise RefreshError()
        else:
            agreeing.add(expected)
            by_id[expected]["package_rows"].append(row)
    oldest = min(sources, key=lambda item: _publisher_instant(item["publisher_cutoff"]["literal"]))
    manifest = {
        "as_of": {
            "basis": "oldest_required_publisher_cutoff",
            "date": None,
            "literal": oldest["publisher_cutoff"]["literal"],
            "representation": "rfc3339",
            "source_ids": [source["source_id"] for source in sources],
        },
        "query_scope": "exact_product_id",
        "source_occurrence_counts": value["selected_occurrence_counts"],
        "sources": sources,
    }
    return package(
        "fedramp",
        binding,
        manifest,
        {"products": products, "unmatched_history": unmatched, "unjoined_packages": unjoined},
    )


def convert(raw: bytes, receipt: object, registry: str, regenerator: Regenerator) -> bytes:
    """Check stored bytes before decoding and decoded bytes before parsing."""
    index = obj(native(receipt))
    if index.get("field_table_sha256") != _TABLE_SHA256:
        raise RefreshError()
    entry = obj(obj(index.get("snapshot_index")).get(registry))
    if entry.get("schema_version") != "1" or entry.get("snapshot_format") != "selected_registry_facts_v1":
        raise RefreshError()
    binding = obj(entry.get("tuple_input"))
    if "tuple_storage" in entry:
        storage = obj(entry["tuple_storage"])
        if storage.get("encoding") != "gzip":
            raise RefreshError()
        verify_bytes(raw, storage)
        raw = _decode_gzip(raw, max_bytes=MAX_BYTES)
        if count(storage.get("decoded_bytes")) != count(binding.get("bytes")) or storage.get(
            "decoded_sha256"
        ) != hash_value(binding.get("sha256")):
            raise RefreshError()
    verify_bytes(raw, binding)
    output = regenerator(parse_source(raw), binding)
    if output["fact_counts"] != entry.get("fact_counts") or digest(
        encode(output["source_manifest"])[:-1]
    ) != hash_value(entry.get("source_manifest_sha256")):
        raise RefreshError()
    encoded = encode(output)
    verify_bytes(encoded, entry)
    if "storage" in entry:
        storage = obj(entry["storage"])
        if (
            storage.get("encoding") != "gzip"
            or count(storage.get("decoded_bytes")) != len(encoded)
            or hash_value(storage.get("decoded_sha256")) != digest(encoded)
        ):
            raise RefreshError()
        encoded = canonical_gzip(encoded)
        verify_bytes(encoded, storage)
    return encoded


def _path(value: Path, *, existing: bool) -> Path:
    path = Path(os.path.abspath(value))
    # Windows alternate streams and device namespaces are not ordinary files.
    if ":" in str(path)[len(path.drive) :] or str(path).startswith(("\\\\?", "\\\\.")):
        raise RefreshError()
    for part in (path, *path.parents):
        try:
            info = part.lstat()
        except FileNotFoundError:
            if part != path or existing:
                raise RefreshError() from None
            continue
        if stat.S_ISLNK(info.st_mode) or getattr(info, "st_file_attributes", 0) & stat.FILE_ATTRIBUTE_REPARSE_POINT:
            raise RefreshError()
        if part == path and existing and not stat.S_ISREG(info.st_mode):
            raise RefreshError()
        if part != path and not stat.S_ISDIR(info.st_mode):
            raise RefreshError()
    return path


def _read(path: Path) -> bytes:
    path = _path(path, existing=True)
    with path.open("rb") as stream:
        before = os.fstat(stream.fileno())
        if not stat.S_ISREG(before.st_mode) or before.st_size > MAX_BYTES:
            raise RefreshError()
        raw = stream.read(MAX_BYTES + 1)
        after = os.fstat(stream.fileno())
    if (
        len(raw) > MAX_BYTES
        or (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns)
        != (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns)
        or len(raw) != before.st_size
    ):
        raise RefreshError()
    return raw


def _distinct(paths: tuple[Path, ...]) -> None:
    for index, left in enumerate(paths):
        for right in paths[index + 1 :]:
            if os.path.normcase(str(left)) == os.path.normcase(str(right)) or (
                left.exists() and right.exists() and os.path.samefile(left, right)
            ):
                raise RefreshError()


def refresh_files(
    input_path: Path, receipt_path: Path, output_path: Path, *, check: bool, registry: str, regenerator: Regenerator
) -> None:
    """Read exactly two explicit files; this is within the 256-file/64-MiB budget."""
    if type(check) is not bool:
        raise RefreshError()
    source, receipt, output = (
        _path(input_path, existing=True),
        _path(receipt_path, existing=True),
        _path(output_path, existing=check),
    )
    _distinct((source, receipt, output))
    raw, receipt_raw = _read(source), _read(receipt)
    encoded = convert(raw, parse_source(receipt_raw), registry, regenerator)
    _distinct((source, receipt, output))
    if check:
        if _read(output) != encoded:
            raise RefreshError()
        return
    if output.exists() and not stat.S_ISREG(output.lstat().st_mode):
        raise RefreshError()
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb", prefix=".registry-refresh-", suffix=".tmp", dir=output.parent, delete=False
        ) as stream:
            temporary = Path(stream.name)
            stream.write(encoded)
            stream.flush()
            os.fsync(stream.fileno())
        _path(output, existing=False)
        _distinct((source, receipt, output))
        os.replace(temporary, output)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink()


def main(registry: str = "fedramp", regenerator: Regenerator = regenerate) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate one reviewed registry snapshot from explicit offline files."
    )
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--receipt", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true", help="compare exact bytes without writing")
    args = parser.parse_args()
    try:
        refresh_files(
            args.input, args.receipt, args.output, check=args.check, registry=registry, regenerator=regenerator
        )
    except (OSError, ValueError, KeyError, TypeError, OverflowError):
        parser.exit(1, "invalid_offline_registry_input\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
