"""Namespace shim so the copied demo overlay imports as ``evidentia.demo``.

Baked into the demo image as ``/opt/evidentia-demo/evidentia/__init__.py``. It
exists ONLY for the launcher's own process (``PYTHONPATH=/opt/evidentia-demo``):
the overlay carries just the ``demo`` leaf, and this marker makes it importable
as ``evidentia.demo`` without pulling in the full package. The runner execs the
real ``evidentia`` binary as a subprocess with a SCRUBBED env (no ``PYTHONPATH``
— see ``evidentia.demo.runner.scrub_env``), so the subprocess imports the full
installed package from site-packages, never this minimal overlay.

Kept as a committed file (not generated by a build-time ``RUN``) so the final
image stage can be built FROM a shell-free distroless base with ``COPY`` only.
"""
