"""No-shell entrypoint for the Tier-1 demo image.

Forwards the container argv to the constrained allowlist runner and exits with
its status. This file is the entire entrypoint surface; the runner enforces the
allowlist, env scrub, and forced ``--offline``. It is baked into the image at a
fixed path and invoked exec-form (``python /opt/evidentia-demo/launch.py``), so
there is no ``/bin/sh`` and no ``-c``/``-m`` at run time — the runner refuses any
off-allowlist argv a caller might pass.

Kept as a committed file (not generated by a build-time ``RUN``) so the final
image stage can be built FROM a shell-free distroless base with ``COPY`` only.
"""

import sys

from evidentia.demo.runner import run

if __name__ == "__main__":
    sys.exit(run(sys.argv[1:]))
