#!/usr/bin/env python
"""Verify the catalog and crosswalk claims the docs and manifest make (v0.13).

`docs/wiki/5-compliance/catalog-inventory.md` states, per redistribution
tier, how many bundled catalogs carry full authoritative text versus
headings only. The manifest (`frameworks.yaml`) declares a `text_depth` per
catalog and a `crosswalk_family` for baselines and maturity levels that
share a parent catalog's crosswalks. None of these claims had a mechanical
check: the inventory table could go stale the moment a catalog's text
changed, a crosswalk could point at a framework id nobody bundles, and a
crosswalk's control ids could silently stop resolving against the catalog
they claim to cover.

This script is that check. Six things must hold:

1. Every manifest entry's declared `text_depth` equals the depth derived
   from the catalog itself (derived, never declared, is the rule; a stale
   or missing value fails).
2. Every `crosswalk_family` value names either a real bundled catalog or a
   family with at least two members, and no member is itself a family.
3. Every crosswalk's `source_framework` and `target_framework` name a real
   bundled catalog, a family, or (target only) a declared external
   framework with no bundled catalog to check against.
4. Every crosswalk's ids resolve against the catalog(s) its framework id
   points at: 100 percent on the source side always, and on the target
   side too unless the target is external.
5. Every Tier C catalog is a stub: `placeholder`, `license_required`, and
   `text_depth == "headings"`.
6. The generated summary block in the inventory wiki page matches what
   this script would render right now.

**What is and is not a failure.** A crosswalk targeting an external
framework (see `EXTERNAL_TARGETS`) that resolves at 0 percent on the target
side is expected and reported, not failed: no bundled catalog exists to
check it against, and the crosswalk is kept because upstream publishes the
mapping anyway. An unknown, non-external framework id is a failure on
either side. Everything in the six checks above is a failure otherwise.

Usage::

    python scripts/check_catalog_truth.py
    python scripts/check_catalog_truth.py --report
    python scripts/check_catalog_truth.py --json
    python scripts/check_catalog_truth.py --write-inventory

Exit codes: ``0`` all six checks pass (or ``--write-inventory`` succeeded),
``1`` drift found.
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from evidentia_core.catalogs.crosswalk import CrosswalkEngine, CrosswalkResolution, resolve_crosswalk
from evidentia_core.catalogs.loader import DATA_DIR, load_any_catalog
from evidentia_core.catalogs.manifest import FrameworkManifestEntry, load_manifest
from evidentia_core.catalogs.registry import FrameworkRegistry, _catalog_entry_ids
from evidentia_core.models.catalog import CrosswalkDefinition

REPO_ROOT = Path(__file__).resolve().parents[1]
MAPPINGS_DIR = REPO_ROOT / "packages" / "evidentia-core" / "src" / "evidentia_core" / "catalogs" / "data" / "mappings"
INVENTORY_PAGE = REPO_ROOT / "docs" / "wiki" / "5-compliance" / "catalog-inventory.md"

#: Redistribution tiers, in the fixed display order the inventory table uses.
TIERS: tuple[str, ...] = ("A", "B", "C", "D")

#: Text-depth values, in the fixed column order the inventory table uses.
DEPTHS: tuple[str, ...] = ("full", "partial", "headings")

#: Crosswalk targets with no bundled catalog to resolve ids against. Kept
#: because upstream publishes the mapping. Resolution is not checked while
#: the target is unbundled; a bundled target still must resolve completely.
EXTERNAL_TARGETS: frozenset[str] = frozenset(
    {
        "eu-cra",  # EU Cyber Resilience Act, no bundled catalog exists for it
        "nist-800-161",  # NIST SP 800-161 (supply chain), no bundled catalog exists for it
        "pci-dss-4.0",  # the upstream OSPS id; the bundled Tier-C stub is "pci-dss-4.0.1"
    }
)

#: How many unresolved ids a resolution failure names before it switches to
#: a count. A crosswalk with hundreds of unresolved rows should not flood
#: the terminal with all of them.
MAX_UNRESOLVED_LISTED = 20

#: Bounds of the generated block this script inserts into and reads back
#: from the inventory wiki page.
BEGIN_MARKER = "<!-- BEGIN catalog-truth (generated by scripts/check_catalog_truth.py) -->"
END_MARKER = "<!-- END catalog-truth -->"

#: The pre-v0.13 sentence and its table's last row. Used exactly once, to
#: locate the hand-written block this gate replaces with the marker block
#: above; every run after that first ``--write-inventory`` finds the
#: markers instead and this path is never reached again.
_LEGACY_SENTENCE = "The current distribution across all"
_LEGACY_LAST_ROW = "| D |"


class CatalogTruthError(RuntimeError):
    """Raised when this gate cannot read something it depends on.

    Fails loudly on purpose, the same way check_public_surface.py's
    SurfaceParseError does: a moved marker or a missing mappings directory
    must not turn the gate into a vacuous pass.
    """


# ── manifest depth (check 1) ───────────────────────────────────────


def load_all_catalogs(entries: Sequence[FrameworkManifestEntry]) -> dict[str, Any]:
    """Load every bundled catalog once, keyed by its manifest id.

    Reused for the depth check and for the --report/--json tables, so a
    catalog is never parsed twice in one run.
    """
    return {entry.id: load_any_catalog(entry.id, custom_path=DATA_DIR / entry.path) for entry in entries}


class BundledCatalogResolver:
    """Resolve ids from bundled files without consulting user catalog imports.

    The normal registry lets user imports shadow the bundle. Documentation
    generators and repository checks need the files named by the bundled
    manifest, so this resolver owns a separate map of their normalized ids.
    """

    def __init__(self, registry: FrameworkRegistry | None = None) -> None:
        self._registry = registry or FrameworkRegistry()
        self.catalogs = load_all_catalogs(self._registry.manifest.frameworks)
        self._ids = {framework_id: _catalog_entry_ids(catalog) for framework_id, catalog in self.catalogs.items()}

    def control_ids_for(self, framework_id: str) -> frozenset[str] | None:
        """Return bundled ids, a family union, or None for an unknown framework."""
        if framework_id in self._ids:
            return self._ids[framework_id]
        members = self._registry.family_members(framework_id)
        if not members:
            return None
        return frozenset(control_id for member in members for control_id in self._ids[member])


def derive_text_depths(catalogs: Mapping[str, Any]) -> dict[str, str]:
    """The computed text_depth of each loaded catalog, keyed by framework id."""
    return {framework_id: catalog.text_depth for framework_id, catalog in catalogs.items()}


def compare_manifest_depth(entries: Sequence[FrameworkManifestEntry], derived: Mapping[str, str]) -> list[str]:
    """A manifest entry's declared text_depth must equal the catalog's derived depth.

    Covers the ``None`` case too: an entry that predates the derivation
    reads as a mismatch against whatever depth its catalog actually has.
    """
    failures: list[str] = []
    for entry in entries:
        actual = derived.get(entry.id)
        if entry.text_depth != actual:
            failures.append(
                f"manifest text_depth for {entry.id} is {entry.text_depth!r}, derived "
                f"{actual!r}; re-run scripts/catalogs/regenerate_manifest.py"
            )
    return failures


# ── crosswalk families (check 2) ───────────────────────────────────


def compare_families(entries: Sequence[FrameworkManifestEntry]) -> list[str]:
    """Every crosswalk_family value must be a real catalog id or a >=2-member family.

    A member of a family may not itself be used as another family's value;
    that would be a nested family, which the engine's single-level
    ``lookup_keys`` cannot express.
    """
    bundled_ids = {entry.id for entry in entries}
    members_of: dict[str, list[str]] = {}
    for entry in entries:
        if entry.crosswalk_family:
            members_of.setdefault(entry.crosswalk_family, []).append(entry.id)

    failures: list[str] = []
    for family, members in sorted(members_of.items()):
        if family in bundled_ids:
            continue
        if len(members) < 2:
            failures.append(
                f"crosswalk_family {family!r} names no bundled catalog and has only "
                f"{len(members)} member(s) ({', '.join(members)}); a family needs at "
                "least two members or must itself be a bundled catalog id"
            )
    for entry in entries:
        if entry.crosswalk_family and entry.id in members_of:
            other_members = ", ".join(sorted(members_of[entry.id]))
            failures.append(
                f"{entry.id!r} is a member of family {entry.crosswalk_family!r} but is "
                f"also used as a family by {other_members}; nested crosswalk families "
                "are not supported"
            )
    return failures


# ── crosswalk framework ids (check 3) ──────────────────────────────


def load_crosswalk_files(mappings_dir: Path) -> list[tuple[str, CrosswalkDefinition]]:
    """Load every crosswalk JSON through the engine's own loader.

    Uses a throwaway CrosswalkEngine (never ``load_all``, never the
    registry's shared engine) so a malformed file raises immediately
    instead of being logged and skipped: a schema break here is a defect
    this gate should crash loudly on, not fold into a formatted failure
    line.
    """
    if not mappings_dir.is_dir():
        raise CatalogTruthError(f"mappings directory not found: {mappings_dir}")
    engine = CrosswalkEngine(mappings_dir=mappings_dir)
    return [(path.name, engine.load_crosswalk(path)) for path in sorted(mappings_dir.glob("*.json"))]


def compare_crosswalk_framework_ids(
    crosswalks: Sequence[tuple[str, CrosswalkDefinition]],
    *,
    bundled_ids: frozenset[str],
    family_ids: frozenset[str],
    external_targets: frozenset[str] = EXTERNAL_TARGETS,
) -> list[str]:
    """A crosswalk's source and target framework ids must name something real.

    The source side must be a bundled catalog or a family (there is always
    something to resolve its ids against). The target side additionally
    accepts a declared external framework, which has no bundled catalog by
    design.
    """
    failures: list[str] = []
    for filename, crosswalk in crosswalks:
        if crosswalk.source_framework not in bundled_ids and crosswalk.source_framework not in family_ids:
            failures.append(
                f"{filename}: source_framework {crosswalk.source_framework!r} is neither "
                "a bundled catalog id nor a crosswalk family"
            )
        if (
            crosswalk.target_framework not in bundled_ids
            and crosswalk.target_framework not in family_ids
            and crosswalk.target_framework not in external_targets
        ):
            failures.append(
                f"{filename}: target_framework {crosswalk.target_framework!r} is neither "
                "a bundled catalog id, a crosswalk family, nor a declared external "
                "target (EXTERNAL_TARGETS in scripts/check_catalog_truth.py)"
            )
    return failures


# ── crosswalk resolution (check 4) ─────────────────────────────────


def compute_resolutions(
    crosswalks: Sequence[tuple[str, CrosswalkDefinition]],
    resolver: BundledCatalogResolver,
) -> list[CrosswalkResolution]:
    """Resolve every crosswalk's ids against the bundled catalog files."""
    resolutions = []
    for filename, crosswalk in crosswalks:
        source_ids = resolver.control_ids_for(crosswalk.source_framework)
        target_ids = resolver.control_ids_for(crosswalk.target_framework)
        resolutions.append(resolve_crosswalk(crosswalk, source_ids=source_ids, target_ids=target_ids, file=filename))
    return resolutions


def _format_unresolved(ids: Sequence[str]) -> str:
    shown = ids[:MAX_UNRESOLVED_LISTED]
    text = ", ".join(shown)
    remaining = len(ids) - len(shown)
    if remaining > 0:
        text += f", and {remaining} more"
    return f"{len(ids)} unresolved: {text}"


def compare_resolutions(
    resolutions: Sequence[CrosswalkResolution],
    *,
    external_targets: frozenset[str] = EXTERNAL_TARGETS,
) -> list[str]:
    """A crosswalk's ids must resolve at 100 percent, except an external target.

    The source side has no external carve-out: every crosswalk names a
    source framework this repo bundles or has a family for, so its ids
    should always resolve. A source that is not even known to the registry
    (an invalid framework id) is left to :func:`compare_crosswalk_framework_ids`
    to report; this function only judges a *known* reference set's ratio.
    """
    failures: list[str] = []
    for res in resolutions:
        if res.source_ids_known and res.source_ratio is not None and res.source_ratio < 1.0:
            pct = round(res.source_ratio * 100)
            failures.append(
                f"{res.file}: source ids for {res.source_framework} resolve {pct}% "
                f"({res.source_resolved}/{res.rows}); {_format_unresolved(res.unresolved_source_ids)}"
            )
        if res.target_framework in external_targets and not res.target_ids_known:
            continue
        if res.target_ids_known and res.target_ratio is not None and res.target_ratio < 1.0:
            pct = round(res.target_ratio * 100)
            failures.append(
                f"{res.file}: target ids for {res.target_framework} resolve {pct}% "
                f"({res.target_resolved}/{res.rows}); {_format_unresolved(res.unresolved_target_ids)}"
            )
    return failures


# ── Tier C invariant (check 5) ─────────────────────────────────────


def compare_tier_c_invariant(entries: Sequence[FrameworkManifestEntry]) -> list[str]:
    """Every Tier C catalog must be a stub: placeholder, license_required, headings."""
    failures: list[str] = []
    for entry in entries:
        if entry.tier != "C":
            continue
        problems: list[str] = []
        if not entry.placeholder:
            problems.append("placeholder is False")
        if not entry.license_required:
            problems.append("license_required is False")
        if entry.text_depth != "headings":
            problems.append(f"text_depth is {entry.text_depth!r} instead of 'headings'")
        if problems:
            failures.append(f"Tier C catalog {entry.id!r} breaks the tier invariant: {'; '.join(problems)}")
    return failures


# ── inventory summary block (check 6) ──────────────────────────────


def compute_tier_depth_counts(
    entries: Sequence[FrameworkManifestEntry], derived: Mapping[str, str]
) -> dict[str, dict[str, int]]:
    """Catalog count per (tier, derived text_depth), for the inventory table."""
    counts: dict[str, dict[str, int]] = {tier: dict.fromkeys(DEPTHS, 0) for tier in TIERS}
    for entry in entries:
        depth = derived.get(entry.id)
        if entry.tier in counts and depth in DEPTHS:
            counts[entry.tier][depth] += 1
    return counts


def render_inventory_block(counts: Mapping[str, Mapping[str, int]], total: int) -> str:
    """The generated block's inner text (no markers), pure given the counts."""
    lines = [
        f"The current distribution across all {total} catalogs, derived from the manifest and the",
        "catalog files themselves (the text depth is computed, never declared):",
        "",
        "| Tier | Catalogs | Full text | Partial text | Headings only |",
        "|---|---|---|---|---|",
    ]
    for tier in TIERS:
        row = counts.get(tier, {})
        full = row.get("full", 0)
        partial = row.get("partial", 0)
        headings = row.get("headings", 0)
        lines.append(f"| {tier} | {full + partial + headings} | {full} | {partial} | {headings} |")
    return "\n".join(lines)


def wrap_marked_block(inner: str) -> str:
    """The inner block text, bounded by the BEGIN/END markers."""
    return f"{BEGIN_MARKER}\n{inner}\n{END_MARKER}"


def _normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n")


def find_marked_block(text: str) -> tuple[int, int] | None:
    """Span of an existing marker block (markers included) in LF-normalized text.

    ``None`` when no BEGIN marker is present. Raises if BEGIN is present
    with no matching END, which would mean the page was hand-edited into a
    broken state.
    """
    start = text.find(BEGIN_MARKER)
    if start == -1:
        return None
    end = text.find(END_MARKER, start)
    if end == -1:
        raise CatalogTruthError(f"found {BEGIN_MARKER!r} with no matching {END_MARKER!r}")
    return start, end + len(END_MARKER)


def find_legacy_block(text: str) -> tuple[int, int] | None:
    """Span of the pre-v0.13 sentence and table this gate replaces on its first run.

    Only reached the first time ``--write-inventory`` runs against a page
    that has never had the marker block; every run after that finds the
    markers via :func:`find_marked_block` instead.
    """
    start = text.find(_LEGACY_SENTENCE)
    if start == -1:
        return None
    row_start = text.find(_LEGACY_LAST_ROW, start)
    if row_start == -1:
        raise CatalogTruthError(
            "found the legacy inventory sentence but not its table's Tier D row; "
            "the page may already have been hand-edited"
        )
    row_end = text.find("\n", row_start)
    if row_end == -1:
        row_end = len(text)
    return start, row_end


def extract_current_block(page_text: str) -> str | None:
    """The inner content of the page's current marker block, or None if absent.

    Tolerates CRLF: the page is normalized to LF before the markers are
    located, so a Windows checkout of the wiki page compares cleanly.
    """
    normalized = _normalize_newlines(page_text)
    span = find_marked_block(normalized)
    if span is None:
        return None
    start, end = span
    return normalized[start + len(BEGIN_MARKER) : end - len(END_MARKER)].strip("\n")


def compare_inventory_block(page_text: str, rendered_inner: str) -> list[str]:
    """The page's current block must equal what this script would render now."""
    current = extract_current_block(page_text)
    if current is None:
        return [
            f"{INVENTORY_PAGE.name} has no catalog-truth marker block; run "
            "scripts/check_catalog_truth.py --write-inventory"
        ]
    if current != rendered_inner:
        return [
            f"the catalog-truth block in {INVENTORY_PAGE.name} does not match the "
            "current manifest; run scripts/check_catalog_truth.py --write-inventory"
        ]
    return []


def write_inventory_page(path: Path, rendered_inner: str) -> None:
    """Rewrite the generated block in place, preserving the page's own line endings."""
    raw = path.read_bytes()
    uses_crlf = b"\r\n" in raw
    normalized = _normalize_newlines(raw.decode("utf-8"))

    new_block = wrap_marked_block(rendered_inner)
    span = find_marked_block(normalized)
    if span is None:
        span = find_legacy_block(normalized)
    if span is None:
        raise CatalogTruthError(
            f"{path}: neither the catalog-truth marker block nor the legacy inventory "
            "sentence/table was found; insert the marker block by hand once"
        )
    start, end = span
    updated = normalized[:start] + new_block + normalized[end:]

    if uses_crlf:
        updated = updated.replace("\n", "\r\n")
    path.write_text(updated, encoding="utf-8", newline="\n")


# ── gathering + orchestration ───────────────────────────────────────


@dataclass
class GateInputs:
    """Everything the six checks and the --report/--json tables read from."""

    entries: list[FrameworkManifestEntry]
    catalogs: dict[str, Any]
    derived_depths: dict[str, str]
    bundled_ids: frozenset[str]
    family_ids: frozenset[str]
    crosswalk_files: list[tuple[str, CrosswalkDefinition]]
    resolutions: list[CrosswalkResolution]
    counts: dict[str, dict[str, int]]
    total: int
    rendered_inner: str


def gather_inputs() -> GateInputs:
    """Load the manifest, every catalog, and every crosswalk once."""
    entries = list(load_manifest().frameworks)
    resolver = BundledCatalogResolver()
    catalogs = resolver.catalogs
    derived_depths = derive_text_depths(catalogs)
    bundled_ids = frozenset(entry.id for entry in entries)
    family_ids = frozenset(entry.crosswalk_family for entry in entries if entry.crosswalk_family)
    crosswalk_files = load_crosswalk_files(MAPPINGS_DIR)
    resolutions = compute_resolutions(crosswalk_files, resolver)
    counts = compute_tier_depth_counts(entries, derived_depths)
    total = sum(sum(depths.values()) for depths in counts.values())
    rendered_inner = render_inventory_block(counts, total)
    return GateInputs(
        entries=entries,
        catalogs=catalogs,
        derived_depths=derived_depths,
        bundled_ids=bundled_ids,
        family_ids=family_ids,
        crosswalk_files=crosswalk_files,
        resolutions=resolutions,
        counts=counts,
        total=total,
        rendered_inner=rendered_inner,
    )


def evaluate(inputs: GateInputs) -> dict[str, list[str]]:
    """Run all six checks against gathered inputs; one failure list per check."""
    return {
        "manifest_depth": compare_manifest_depth(inputs.entries, inputs.derived_depths),
        "families": compare_families(inputs.entries),
        "framework_ids": compare_crosswalk_framework_ids(
            inputs.crosswalk_files,
            bundled_ids=inputs.bundled_ids,
            family_ids=inputs.family_ids,
        ),
        "resolution": compare_resolutions(inputs.resolutions),
        "tier_c": compare_tier_c_invariant(inputs.entries),
        "inventory_block": compare_inventory_block(INVENTORY_PAGE.read_text(encoding="utf-8"), inputs.rendered_inner),
    }


def run_all_checks() -> list[str]:
    """All current failures against the real repo, flattened in check order."""
    results = evaluate(gather_inputs())
    return [message for messages in results.values() for message in messages]


# ── --report / --json tables ────────────────────────────────────────


def build_catalog_rows(entries: Sequence[FrameworkManifestEntry], catalogs: Mapping[str, Any]) -> list[dict[str, Any]]:
    rows = []
    for entry in entries:
        catalog = catalogs[entry.id]
        statement_rows = catalog.statement_rows()
        rows.append(
            {
                "id": entry.id,
                "tier": entry.tier,
                "category": entry.category,
                "entries": len(statement_rows),
                "withdrawn_entries": sum(1 for row in statement_rows if row.withdrawn),
                "text_depth": catalog.text_depth,
                "crosswalk_family": entry.crosswalk_family or "",
                "source": catalog.source,
            }
        )
    return rows


def _display_resolution(known: bool, resolved: int, total: int) -> str:
    if not known:
        return "not bundled"
    pct = 100 if total == 0 else round(100 * resolved / total)
    return f"{resolved}/{total} ({pct}%)"


def build_crosswalk_rows(resolutions: Sequence[CrosswalkResolution]) -> list[dict[str, Any]]:
    return [
        {
            "file": res.file,
            "source": res.source_framework,
            "target": res.target_framework,
            "rows": res.rows,
            "source_resolved": _display_resolution(res.source_ids_known, res.source_resolved, res.rows),
            "target_resolved": _display_resolution(res.target_ids_known, res.target_resolved, res.rows),
        }
        for res in resolutions
    ]


def print_catalog_table(rows: Sequence[Mapping[str, Any]]) -> None:
    print(f"{'ID':<32} {'Tier':<4} {'Category':<12} {'Entries':>7} {'Withdrawn':>9} {'Depth':<9} {'Family':<18} Source")
    for row in rows:
        print(
            f"{row['id']:<32} {row['tier']:<4} {row['category']:<12} {row['entries']:>7} "
            f"{row['withdrawn_entries']:>9} {row['text_depth']:<9} {row['crosswalk_family']:<18} {row['source']}"
        )


def print_crosswalk_table(rows: Sequence[Mapping[str, Any]]) -> None:
    print(f"{'File':<52} {'Source':<24} {'Target':<20} {'Rows':>5} {'Src resolved':<16} Tgt resolved")
    for row in rows:
        print(
            f"{row['file']:<52} {row['source']:<24} {row['target']:<20} {row['rows']:>5} "
            f"{row['source_resolved']:<16} {row['target_resolved']}"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        action="store_true",
        help="print a per-catalog table and a per-crosswalk table before the summary",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit the report and the failures as one JSON object instead of text",
    )
    parser.add_argument(
        "--write-inventory",
        action="store_true",
        help="rewrite the generated summary block in the inventory wiki page and exit",
    )
    args = parser.parse_args(argv)

    inputs = gather_inputs()

    if args.write_inventory:
        write_inventory_page(INVENTORY_PAGE, inputs.rendered_inner)
        rel = INVENTORY_PAGE.relative_to(REPO_ROOT)
        print(f"check_catalog_truth: wrote the inventory summary block to {rel} ({inputs.total} catalogs).")
        return 0

    results = evaluate(inputs)
    failures = [message for messages in results.values() for message in messages]

    if args.json:
        payload = {
            "ok": not failures,
            "catalogs": build_catalog_rows(inputs.entries, inputs.catalogs),
            "crosswalks": build_crosswalk_rows(inputs.resolutions),
            "tier_depth_counts": inputs.counts,
            "failures": failures,
        }
        print(json.dumps(payload, indent=2))
        return 0 if not failures else 1

    if args.report:
        print_catalog_table(build_catalog_rows(inputs.entries, inputs.catalogs))
        print()
        print_crosswalk_table(build_crosswalk_rows(inputs.resolutions))
        print()

    total_rows = sum(res.rows for res in inputs.resolutions)
    tier_c_count = sum(1 for entry in inputs.entries if entry.tier == "C")
    family_word = "family" if len(inputs.family_ids) == 1 else "families"

    print(f"  manifest depth:          {len(inputs.entries)} catalog(s), {len(results['manifest_depth'])} mismatch(es)")
    print(f"  crosswalk families:      {len(inputs.family_ids)} {family_word}, {len(results['families'])} malformed")
    print(f"  crosswalk framework ids: {len(inputs.crosswalk_files)} file(s), {len(results['framework_ids'])} invalid")
    print(f"  crosswalk resolution:    {total_rows} row(s), {len(results['resolution'])} below threshold")
    print(f"  tier C invariant:        {tier_c_count} catalog(s), {len(results['tier_c'])} violation(s)")
    print(f"  inventory block:         {'current' if not results['inventory_block'] else 'stale'}")

    if failures:
        print()
        print(f"CATALOG TRUTH DRIFT ({len(failures)}):")
        for failure in failures:
            print(f"  - {failure}")
        print()
        print("check_catalog_truth: FAIL")
        return 1

    print()
    print(
        "check_catalog_truth: PASS. The catalog inventory and crosswalks match the manifest and the bundled catalogs."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
