import { Terminal } from "lucide-react";
import { useEffect, useRef } from "react";

/**
 * Self-hosted asciinema-player descriptor. We vendor the pinned 3.15.1 bundle
 * into `public/vendor/` (Apache-2.0, no CDN — air-gap-on-brand) and load it
 * lazily from here so the normal production console never pays for the ~177 kB
 * player: the assets are injected only when this route mounts.
 */
const PLAYER_VERSION = "3.15.1";
const PLAYER_JS = `/vendor/asciinema-player/${PLAYER_VERSION}/asciinema-player.min.js`;
const PLAYER_CSS = `/vendor/asciinema-player/${PLAYER_VERSION}/asciinema-player.css`;
/** The committed Meridian-v2 cast (Tier 0 artifact, generated by gen_cast.py). */
const CAST_SRC = "/demo.cast";

/** Minimal surface of the global the standalone bundle exposes on `window`. */
interface AsciinemaPlayerGlobal {
  create: (
    src: string,
    el: HTMLElement,
    opts?: Record<string, unknown>,
  ) => { dispose?: () => void };
}

declare global {
  interface Window {
    AsciinemaPlayer?: AsciinemaPlayerGlobal;
  }
}

/** Inject a `<link rel=stylesheet>` once; tagged so the page can find it. */
function ensureStylesheet(): void {
  if (document.querySelector('link[data-asciinema-player]')) {
    return;
  }
  const link = document.createElement("link");
  link.rel = "stylesheet";
  link.href = PLAYER_CSS;
  link.dataset.asciinemaPlayer = "";
  document.head.appendChild(link);
}

/**
 * Inject the pinned bundle once and resolve when `window.AsciinemaPlayer` is
 * available. Subsequent mounts reuse the already-loaded global.
 */
function loadPlayer(): Promise<AsciinemaPlayerGlobal> {
  if (window.AsciinemaPlayer) {
    return Promise.resolve(window.AsciinemaPlayer);
  }
  const existing = document.querySelector<HTMLScriptElement>(
    'script[data-asciinema-player]',
  );
  return new Promise((resolve, reject) => {
    const onReady = () => {
      if (window.AsciinemaPlayer) {
        resolve(window.AsciinemaPlayer);
      } else {
        reject(new Error("asciinema-player loaded but exposed no global"));
      }
    };
    if (existing) {
      existing.addEventListener("load", onReady, { once: true });
      existing.addEventListener(
        "error",
        () => reject(new Error("failed to load the asciinema-player bundle")),
        { once: true },
      );
      return;
    }
    const script = document.createElement("script");
    script.src = PLAYER_JS;
    script.async = true;
    script.dataset.asciinemaPlayer = "";
    script.addEventListener("load", onReady, { once: true });
    script.addEventListener(
      "error",
      () => reject(new Error("failed to load the asciinema-player bundle")),
      { once: true },
    );
    document.body.appendChild(script);
  });
}

/**
 * Tier 0 demo surface — the self-hosted asciinema cast of the real Meridian-v2
 * CLI sequence. Mounts the vendored player against the committed `/demo.cast`;
 * no backend, no network (the assets and the cast are same-origin static
 * files). Lives behind the `IS_DEMO` route registration so it ships only in the
 * static demo bundle.
 */
export function DemoPage() {
  const mountRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = mountRef.current;
    if (!el) {
      return;
    }
    let player: { dispose?: () => void } | undefined;
    let cancelled = false;

    ensureStylesheet();
    loadPlayer()
      .then((api) => {
        if (cancelled || !mountRef.current) {
          return;
        }
        player = api.create(CAST_SRC, el, {
          // Calm autoplay for a hands-off evaluator; the controls stay visible.
          autoPlay: true,
          loop: false,
          idleTimeLimit: 2,
          theme: "asciinema",
          fit: "width",
          terminalFontSize: "14px",
        });
      })
      .catch((err: unknown) => {
        // Non-fatal: the page still explains what the recording shows.
        console.error("Failed to mount the asciinema player", err);
      });

    return () => {
      cancelled = true;
      player?.dispose?.();
      // Clear the captured mount so a re-mount (StrictMode double-invoke)
      // starts fresh; `el` is the node this effect bound to.
      el.replaceChildren();
    };
  }, []);

  return (
    <div className="stack-8">
      <header className="stack-2">
        <h1 className="page-title">Watch it run</h1>
        <p className="page-sub">
          A recording of the real <code className="kbd">evidentia</code> CLI
          running a full gap analysis on the{" "}
          <strong>Meridian Financial</strong> fintech inventory — catalog
          listing, NIST 800-53 + SOC 2 gap analysis, OSCAL Assessment Results
          emit, and signed-artifact verification. No edits, no backend.
        </p>
      </header>

      <section
        role="region"
        aria-label="asciinema recording of the Evidentia CLI"
        className="overflow-hidden rounded-lg border border-border bg-[#121314] p-2"
      >
        <div ref={mountRef} />
      </section>

      <aside className="box muted flex items-start gap-2 text-sm">
        <Terminal className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" aria-hidden />
        <span>
          The same sequence is in the README Quickstart. Every command shown is
          a current, frozen CLI verb — try them yourself after{" "}
          <code className="kbd">pip install evidentia</code>.
        </span>
      </aside>
    </div>
  );
}
