"""Hatchling build hook: embed the per-package SBOM (PEP 770).

Injects sbom/*.cdx.json into the wheel's .dist-info/sboms/ when present
(generated by scripts/gen_package_sboms.py — gitignored; release.yml
generates before building and its presence gate guarantees published
wheels carry it). Skips cleanly when absent so fresh-clone uv sync /
uv build never depend on the generator. sdist artifacts = ["sbom/"] in
pyproject.toml carries the generated files through the sdist->wheel
release path (hatchling's default sdist selection respects VCS-ignore).
"""

import os

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


class SbomBuildHook(BuildHookInterface):
    PLUGIN_NAME = "custom"

    def initialize(self, version, build_data):
        if self.target_name != "wheel":
            return
        sbom_dir = os.path.join(self.root, "sbom")
        if not os.path.isdir(sbom_dir):
            return
        files = sorted(
            os.path.join(sbom_dir, f)
            for f in os.listdir(sbom_dir)
            if f.endswith(".cdx.json")
        )
        build_data.setdefault("sbom_files", []).extend(files)
